### ISSUE TITLE
What is the difference between schema-registry-start of kafka_connect 1.0.1 and kafka_connect 3.0.1?

### ISSUE THREAD

**Issue by Janaarthan** [confluentinc/kafka-connect-hdfs#120]
While running schema-registry-start of kafka_connect 3.0.1, the following exceptions are coming.  May I know how to resolve this?

[2016-09-22 15:55:12,108] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain:51)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading field 'host': Error reading string of length 24947, only 114 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
        at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:178)
        at org.apache.kafka.clients.consumer.internals.Fetcher.getTopicMetadata(Fetcher.java:205)
        at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1272)
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread.<init>(KafkaStoreReaderThread.java:107)
        at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:143)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:164)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:55)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:37)
        at io.confluent.rest.Application.createServer(Application.java:117)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:43)
        at io.confluent.kafka.schemaregistry.rest.Main.main(Main.java:34)

Thanks,
M, Janaarthan.

**Comment by cotedm** [comment]
Looks like maybe you are trying to use the Schema Registry with a down-level version of the broker? Your broker version must be greater than or equal to that of your clients. For your reference, you can use the Schema Registry repo for questions around that product. https://github.com/confluentinc/schema-registry

Closing this issue as it is not relevant to this connector.
