### ISSUE TITLE
Example task cant find AvroData

### ISSUE THREAD

**Issue by manugarri** [confluentinc/kafka-connect-hdfs#149]
Im not sure if this is a bug , or if this is just a usage question (can't seem to find any SO topics on the matter).

I am using kafka-connect 3.0.1 and kafka 0.10  (Scala 2.10).

I am running a simple task with a source from a text file (using the `connect-file-source.properties` unmodified) as a source:
```
name=local-file-source
connector.class=FileStreamSource
tasks.max=1
file=test.txt
topic=connect-test
```
and the `quickstart-hdfs.properties` as the sink (changing the topic to match that of the sink file):
```
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=connect-test
hdfs.url=hdfs://localhost:9000
flush.size=1
```

I am running it with the default `connect-standalone.properties`:

```
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
```

I built the `kafka-connect-hdfs-3.0.1.jar` using maven (`mvn clean install`) and put it in the libs folder in the kafka directory.

However when I run the command like 
```
./bin/connect-standalone.sh config/connect-standalone.properties config/connect-file-source.properties config/quickstart-hdfs.properties
```

I get the following error:

```
(io.confluent.connect.hdfs.HdfsSinkConnectorConfig:178)
[2016-11-08 18:52:16,690] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.NoClassDefFoundError: io/confluent/connect/avro/AvroData
	at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:63)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.confluent.connect.avro.AvroData
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
```

It seems that HdfsSinkTask.java is looking for the class `io/confluent/connect/avro/AvroData` , but in the `kafka-connect-hdfs-3.0.1.jar` avro related classes are defined in  `io/confluent/connect/hdfs/avro`

Is this an issue, or am I installing the kafka-hdfs connector wrongly? I apologize for the long issue but can´t find any documentation on the topic.

**Comment by ewencp** [comment]
The jar doesn't include all its dependencies, you'll need all the dependencies as well. The `package` target collects all the dependencies in the `target/kafka-connect-hdfs-3.1.0-SNAPSHOT-package/share/java/kafka-connect-hdfs/` directory, which is probably the easiest way to collect them all. If you put those on the classpath then it should work.

(Note, of course, that you could also get this just by downloading our 3.0.1 release [here](https://www.confluent.io/download).)

**Comment by manugarri** [comment]
I see, thanks for your answer. I downloaded the Confluent platform tar file from http://docs.confluent.io/3.0.1/installation.html#installation-archive

However, after unzipping, cant see any jar or pom/sbt file to build the dependencies for kafka-connect-hdfs. Is there any way to get all the dependencies (maybe as an uber jar?)

**Comment by manugarri** [comment]
Ok, I just copied the contents of `package/share/java/kafka-connect-hdfs` to `/libs` and that seems to have done the trick as you said.

Thanks so much for your help!
