### ISSUE TITLE
Issue sending Large set of data to kafka

### ISSUE THREAD

**Issue by bijums** [confluentinc/kafka-connect-hdfs#153]
@ewencp 
The below mentioned exception is obtained when we try to run more than 1000 records into Kafka through Producer java program . We are using confluent-2.0.0 and hortonworks sanbox 2.4.
Can you help me to find the reason? 

**Caused by: java.lang.IllegalStateException: Too many sma objects created for demo-value!
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:88)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
        at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:54)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:424)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:339)
        at ProducerAvro.postMessageToKafka(ProducerAvro.java:57)
        at ProducerAvro.main(ProducerAvro.java:120)**

**Comment by cotedm** [comment]
@bijums this happens when you create more schemas per subject than is allowed by this config: `max.schemas.per.subject`. You can raise that value if you need more schemas for a particular subject. FYI -- this is more of a schema registry issue, so I will close this issue. You can use (this repo)[https://github.com/confluentinc/schema-registry] or (the mailing list)[https://groups.google.com/forum/#!forum/confluent-platform] if you have further questions around this parameter.

**Comment by arrajeev87** [comment]
Hi we are facing a similar issue here. However we have only a single schema per subject. The schema is sent with the value all the time. I was looking at the class CachedSchemaRegistryClient, we are using an IdentityHashMap to store schema and schemaId. However the schema instance is not same all the time which results in the map size increasing. Am I doing anything wrong here? Any help is much appreciated
