### ISSUE TITLE
NullPointerException: Task is being killed and will not recover until manually restarted

### ISSUE THREAD

**Issue by krisskross** [confluentinc/kafka-connect-hdfs#159]
Hi

Noticed a NPE which cause the task to stop and never recover.

Cheers,
-Kristoffer

java.lang.NullPointerException
	at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:549)
	at io.confluent.connect.hdfs.TopicPartitionWriter.close(TopicPartitionWriter.java:360)
	at io.confluent.connect.hdfs.DataWriter.close(DataWriter.java:296)
	at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:121)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:435)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:147)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cotedm** [comment]
@krisskross can you clarify which version you are running and provide the full stack trace if this isn't it?

**Comment by krisskross** [comment]
We haven't seen this in a while and I have a hard time tracing it back to the exact version. Let's close until it surface again.

**Comment by shuhanding** [comment]
Hi @cotedm 

I got NPE like:
[2017-05-25 19:09:46,376] ERROR Task hdfs-sink threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.NullPointerException
	at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:121)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:317)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-05-25 19:09:46,376] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)

I am using 3.2.1.

**Comment by debasishg** [comment]
I also faced a similar error today ..

[2017-07-18 18:10:31,783] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.NullPointerException
	at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:121)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:317)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-18 18:10:31,783] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)

I am using 3.2.2 and the following kafka connect command ..

```bash
bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties etc/kafka-connect-hdfs/quickstart-hdfs.properties
```

**Comment by debasishg** [comment]
Ok, found the reason for the NullPointer. The HDFS address in `etc/kafka-connect-hdfs/quickstart-hdfs.properties` was not correct. Still the error is very misleading and doesn't reveal the exact reason ..

**Comment by jtuberville** [comment]
I saw the same issue when misconfiguring the hdfs url in one of my connectors. In my case the hdfs.url was pointing to a one cluster while the hadoop.conf.dir was pointed to another cluster's config files.

**Comment by timvw** [comment]
Having the same with kafka-connect-hdfs-4.0.0.jar

      java.lang.NullPointerException\n
      \tat io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:119)\n
      \tat org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:363)\n
      \tat org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:547)\n
      \tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)\n
      \tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n
      \tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n
      \tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n
      \tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n
      \tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n
      \tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n
      \tat java.lang.Thread.run(Thread.java:748)\n",

**Comment by qgeffard** [comment]
having the same (i think) with 3.3.0 :


```
state: "FAILED",
trace: "java.lang.NullPointerException at io.confluent.connect.hdfs.DataWriter.close(DataWriter.java:296) at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:121) at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:323) at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:486) at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748)
```

**Comment by timvw** [comment]
Sadly the code does not handle failures in HDFS authentication (ugi is null) and results in a nullpointerexception further down..

**Comment by bkotesh** [comment]
@debasishg @timvw @jtuberville 
While checking the status of the hdfs-sing , iam getting error as below. Please help to resolve this issue.

 ./bin/confluent status hdfs-sink
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

{
  "name": "hdfs-sink",
  "connector": {
    "state": "RUNNING",
    "worker_id": "192.168.20.220:8083"
  },
  "tasks": [
    {
      "state": "FAILED",
      "trace": "java.lang.NullPointerException\n\tat io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:135)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:397)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:616)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:197)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n",
      "id": 0,
      "worker_id": "192.168.20.220:8083"
    },
