### ISSUE TITLE
Kafka Topic not writing JSON data to HDFS

### ISSUE THREAD

**Issue by NishantVerma07** [confluentinc/kafka-connect-hdfs#165]
My scenario:

I have one source which is dumping **JSON** data into already setup KAFKA. It creates multiple topics with multiple partitions and dumps data into respective topics. 

My task is to flush this data from KAFKA topics into HDFS cluster (present in different server). 

I downloaded confluent-3.1.1 in the KAFKA server and did below changes:

a- Updated quickstart-hdfs.properties with topic names and hdfs.url. All the topics which are generated at the KAFKA end are written here comma separated. 
b- Updated  connect-avro-standalone.properties as below:
===================================================================
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
key.converter.schema.registry.url=http://localhost:8081
value.converter.schema.registry.url=http://localhost:8081
enable.auto.commit=true
auto.commit.interval.ms=1000
offset.flush.interval.ms=1000
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.topic=_offsets
offset.storage.file.filename=/opt/confluent-3.1.1/connect.offsets
===================================================================
c- Created a blank file /opt/confluent-3.1.1/connect.offsets and given write permissions to it.

Now, my source is dumping JSON data into KAFKA topics. I started schema registry(./bin/schema-registry-start ./etc/schema-registry/schema-registry.properties ) and then started KAFKA connect (./bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties \
etc/kafka-connect-hdfs/quickstart-hdfs.properties). 

The console where I start KAFKA connect gives below o/p:
==================================================================

[2017-01-17 14:00:16,166] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-369, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,166] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-124, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,167] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-264, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,167] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-130, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,167] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-0, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,167] INFO Fetch offset 0 is out of range for partition Prd_IN_GeneralEvents-10, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,169] INFO Fetch offset 0 is out of range for partition Prd_IN_Processed_Alert-8, resetting offset (org.apache.kafka.clients.consumer.internals.Fetcher:708)
[2017-01-17 14:00:16,171] INFO WorkerSinkTask{id=hdfs-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-01-17 14:00:16,368] INFO WorkerSinkTask{id=hdfs-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-01-17 14:00:16,391] INFO WorkerSinkTask{id=hdfs-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-01-17 14:00:16,522] INFO WorkerSinkTask{id=hdfs-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-01-17 14:00:16,535] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
        at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:368)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:357)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'aa8c0c3a49e14b0c8bcaf1e2f082830b': was expecting ('true', 'false' or 'null')
at [Source: [B@3b7fb2eb; line: 1, column: 65]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'aa8c0c3a49e14b0c8bcaf1e2f082830b': was expecting ('true', 'false' or 'null')
at [Source: [B@3b7fb2eb; line: 1, column: 65]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3323)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2482)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3604)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2161)
        at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:23)
        at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:363)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:357)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
[2017-01-17 14:00:16,537] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2017-01-17 14:00:17,760] INFO Reflections took 8075 ms to scan 264 urls, producing 12033 keys and 80037 values  (org.reflections.Reflections:229)
 
==================================================================

Hence nothing happens on HDFS. 
**Where am I missing the configuration or point?**

If I try the example present in confluent website (create AVRO-CONSOLE-PRODUCER and write {"f1": "value1"} data in the console), data gets written into HDFS properly without any issues.

Have also tried with below changes in connect-avro-standalone.properties file, but with error as:

key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter

==================================================================
Error1:
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 45)): Expected space separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core
==================================================================

==================================================================
Error2:
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core
==================================================================

==================================================================
Error3:
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('7fa1b2e9-70ce-4ded-9842-f3b9115e0932' (code 45)): Expected "true","false",null separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: [B@3c0b4f6b; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core
==================================================================

**Where am I missing the link here?**

**Comment by cotedm** [comment]
This is being addressed here [https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/confluent-platform/2xfUtXIg4w4/uKQHxlHbCAAJ]
