### ISSUE TITLE
Schema evolution on distributed environnement

### ISSUE THREAD

**Issue by pmpinson** [confluentinc/kafka-connect-hdfs#167]
Hello,

We have issue when evolving the schema of our messages.
We have few small kafka clusters of 2-3 nodes around the world (5 Datacenter's). Our applications generate messages in those remote DC.
Then all messages are pushed to a central kafka with mirror maker in another datacenter. The central kafka can also received messages from applications deploy in the DC.
The kafka connect is deploy in same DC as the central kafka.
We use hdfs connect to output to our hadoop cluster and hive.
We use Confluent Plateform 3.0.0 with schema registry and the kafka from confluent package.

1) 1 Data center (what we saw in preprod)
All seems to be good when only 1 applications / 2 instances / 1 Datacenter.
We are running version 1 of schema.
We deploy new version that generate messages on new format. The registry create the new version 2 and the connect produce message on hdfs.

2) Multi Data center
We do blue/green deployement on 1 DC and then deploy few minutes later on others DC.
The first deployed DC have generate the next version 2. But others DC steel produce version 1.
The connect stop working facing an different schema.

The evolution we do here is a refactoring of the scala class (using avro'4s) that generate a change on the package so on the namespace. But we planned to add fields.

`Jan 26 03:33:06 mtl-vm-kaf-connect01.streamtheworld.net java[4029]: ERROR Task yieldop-auction-hdfs-7 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask)
                                                                    java.lang.RuntimeException: org.apache.kafka.connect.errors.SchemaProjectorException: Schema name mismatch. source name: com.p1.p2.LogLine and target name: com.p1.LogLine
                                                                            at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:292)
                                                                            at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:234)
                                                                            at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:91)
                                                                            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:370)
                                                                            at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
                                                                            at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
                                                                            at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
                                                                            at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
                                                                            at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
                                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                                                                            at java.lang.Thread.run(Thread.java:745)
                                                                    
Caused by: org.apache.kafka.connect.errors.SchemaProjectorException: Schema name mismatch. source name: com.p1.p2.LogLine and target name: com.p1.LogLine
                                                                            at org.apache.kafka.connect.data.SchemaProjector.checkMaybeCompatible(SchemaProjector.java:132)
                                                                            at org.apache.kafka.connect.data.SchemaProjector.project(SchemaProjector.java:59)
                                                                            at io.confluent.connect.hdfs.schema.SchemaUtils.project(SchemaUtils.java:66)
                                                                            at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:263)
                                                                            ... 13 more`

Last piece of information, each night we compact generated files for a day in a one / few files, we lost extra information like avro format...

Actually we are stuck we can't get the connect working. We tried to remove the bad messages by changing retention policy of the topic, but after restarting connect have the same error.

Any suggestion to solve the problem ?
How can we handle such future deployment ?

Thanks for help

**Comment by cotedm** [comment]
@pmpinson are you using the Schema Registry to manage your schemas? If you are, you should be deploying it like this: http://docs.confluent.io/3.1.1/schema-registry/docs/deployment.html#multi-dc-setup This type of setup can help you avoid problems like this in the future.

To get out of the immediate situation, you can probably just configure the connector to use a new topic then move the "good data" from the old topic to the new one to make sure you got everything cleaned out. I'd start there anyway.

**Comment by pmpinson** [comment]
Thanks, for the reply, i will look into the setup you point out to me.

To get out of the situation, i backup the entire kafka, so i can reprocess all the missing messages. Then i dropped all messages by changing the retention policy to remove messages with old schema.

After this clean of kafka, connect won't start (it was doing nothing and say nothing in log) so to get back in track i :
- drop connect task,
- clean all temporary folder in hdfs,
- move hdfs (hive) result folder to avoid connect to try to calculate the last offset,
- recreate task.
After consuming restart, i moved back my hive folder to have my entire data in the good folder.

**Comment by cotedm** [comment]
Thanks for the followup! I'm glad you got it recovered.
