### ISSUE TITLE
Issue parsing hdfs connector config via json to kafka connect in distibuted mode

### ISSUE THREAD

**Issue by jatinderjawanda** [confluentinc/kafka-connect-hdfs#185]
Hi,
we encountered a issue in which we tried to parse a property "path.format='time'=YYYYMMddHHmm/" is giving error in kafka-connect distributed mode. we are using same property in standalone mode and is working as expected.

Below is the config for hdfs sink connector used for distributed mode:
----------------------------------------------------------------------
curl -X POST -H "Content-Type: application/json" --data '{"name": "httpPDM-sink", "config": {"connector.class":"io.confluent.connect.hdfs.HdfsSinkConnector", "tasks.max":"1", "hdfs.url":"hdfs://nameservice:8020", "hadoop.conf.dir":"/etc/hadoop/conf/", "hadoop.home":"/usr/lib/hadoop/", "hive.conf.dir":"/etc/hive/conf/", "hive.home":"/usr/lib/hive/", "flush.size":"1", "format.class":"io.confluent.connect.hdfs.parquet.ParquetFormat", "hive.integration":"true", "hive.database":"topic_data", "hive.metastore.uris":"thrift://localhost:9083", "schema.compatibility":"BACKWARD", "partitioner.class":"io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner", "partition.duration.ms":"300000", "path.format":"'time'=YYYYMMddHHmm/", "rotate.interval.ms":"300000", "locale":"en", "timezone":"Etc/UTC", "topics":"topic5" }}' http://localhost:8083/connectors

Error we are seeing :
---------------------
[2017-04-19 16:53:52,647] INFO HdfsSinkConnectorConfig values:
	connect.hdfs.keytab =
	connect.hdfs.principal =
	filename.offset.zero.pad.width = 10
	flush.size = 1
	format.class = io.confluent.connect.hdfs.parquet.ParquetFormat
	hadoop.conf.dir = /etc/hadoop/conf/
	hadoop.home = /usr/lib/hadoop/
	hdfs.authentication.kerberos = false
	hdfs.namenode.principal =
	hdfs.url = hdfs://srx:8020
	hive.conf.dir = /etc/hive/conf/
	hive.database = jj_data
	hive.home = /usr/lib/hive/
	hive.integration = true
	hive.metastore.uris = thrift://192.168.115.234:9083
	kerberos.ticket.renew.period.ms = 3600000
	locale = en
	logs.dir = logs
	partition.duration.ms = 300000
	partition.field.name =
	partitioner.class = io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner
	path.format = time=YYYYMMddHHmm/
	retry.backoff.ms = 5000
	rotate.interval.ms = 300000
	rotate.schedule.interval.ms = -1
	schema.cache.size = 1000
	schema.compatibility = BACKWARD
	shutdown.timeout.ms = 3000
	storage.class = io.confluent.connect.hdfs.storage.HdfsStorage
	timezone = Etc/UTC
	topics.dir = topics
 (io.confluent.connect.hdfs.HdfsSinkConnectorConfig:180)
[2017-04-19 16:53:52,895] INFO Hadoop configuration directory /etc/hadoop/conf/ (io.confluent.connect.hdfs.DataWriter:93)
[2017-04-19 16:53:53,411] WARN Unable to load native-hadoop library for your platform... using builtin-java classes where applicable (org.apache.hadoop.util.NativeCodeLoader:62)
[2017-04-19 16:53:54,122] WARN The short-circuit local reads feature cannot be used because libhadoop cannot be loaded. (org.apache.hadoop.hdfs.shortcircuit.DomainSocketFactory:117)
[2017-04-19 16:53:54,304] ERROR Task httpPDM-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.IllegalArgumentException: Illegal pattern component: t
	at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566)
	at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687)
	at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177)
	at io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner.getDateTimeFormatter(TimeBasedPartitioner.java:52)
	at io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner.init(TimeBasedPartitioner.java:47)
	at io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner.configure(TimeBasedPartitioner.java:91)
	at io.confluent.connect.hdfs.DataWriter.createPartitioner(DataWriter.java:398)
	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:178)
	at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:76)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-19 16:53:54,306] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)

Regards,
Jatinder Jawanda

**Comment by codenamelxl** [comment]
Try to replace this part

> "path.format":"'time'=YYYYMMddHHmm/"
 with

> "path.format":"time=YYYYMMddHHmm"

That should get it to work.

**Comment by jatinderjawanda** [comment]
Hi Lee,

I tried your suggestion, but it didn't work.Same exception is coming that i pasted above.

However, i was able to run it like this.
"path.format" :"YYYYMMddHHmm" 

Regards,
Jatinder Jawanda

**Comment by jatinderjawanda** [comment]
FYI, we have managed to make it work for "path.format":"'time'=YYYYMMddHHmm" using firefox rest client plugin.

But somehow, now it seems curl command is the culprit.

**Comment by ewencp** [comment]
FYI, the problem with the curl command was unescaped single quotes, which is the quote you had used for the entire data:
```
"'time'=YYYYMMddHHmm/"
```
You'd need to escape the `'`'s around `'time'` for this to work on the command line.

**Comment by shuhanding** [comment]
@ewencp how to escape it? do you mean: 
    "\'time\'=YYYYMMddHHmm/"
