### ISSUE TITLE
The problems is kafka to hdfs Use time range

### ISSUE THREAD

**Issue by feloxx** [confluentinc/kafka-connect-hdfs#186]
jps
```
2656 DataNode
3025 DFSZKFailoverController
2865 JournalNode
3300 ResourceManager
6248 Jps
1769 Worker
3385 JobHistoryServer
410 SupportedKafka
2538 NameNode
6028 SchemaRegistryMain
3165 NodeManager
2111 QuorumPeerMain
```

---

topics

```
[hadoop1@hadoop1 etc]$ kafka-topics --list --zookeeper hadoop1:2181
__consumer_offsets
_schemas
filetime1
filetime2
test
time1
[hadoop1@hadoop1 etc]$ 
[hadoop1@hadoop1 etc]$ 
[hadoop1@hadoop1 etc]$ kafka-run-class kafka.tools.GetOffsetShell --broker-list localhost:9092 --topic time1 --time -1         
time1:0:506

```

---

schema-registry/schema-registry.properties

```
listeners=http://0.0.0.0:8081
kafkastore.connection.url=hadoop1:2181,hadoop2:2181,hadoop3:2181,hadoop4:2181,hadoop5:2181
kafkastore.topic=_schemas
debug=true
```

---

kafka-connect-hdfs/quickstart-hdfs.properties

```
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=time1
hdfs.url=hdfs://hadoop1:8020
flush.size=100
rotate.interval.ms=100000
hadoop.conf.dir=/home/hadoop1/softs/confluent-3.2.0/etc/kafka-connect-hdfs
```

---

start
`bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties etc/kafka-connect-hdfs/quickstart-hdfs.properties`

---

problem
```
[2017-04-20 16:01:36,817] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.DataException: time1
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:92)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:401)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:249)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id -469682127
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found io.confluent.rest.exceptions.RestNotFoundException: Schema not found
io.confluent.rest.exceptions.RestNotFoundException: Schema not found
        at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.schemaNotFoundException(Errors.java:58)
        at io.confluent.kafka.schemaregistry.rest.resources.SchemasResource.getSchema(SchemasResource.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:548)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:489)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:426)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
; error code: 40403
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:170)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:188)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:330)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:323)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:63)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndID(CachedSchemaRegistryClient.java:118)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:121)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:190)
        at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:113)
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:82)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:401)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:249)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-20 16:01:36,835] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
```

please help me

**Comment by feloxx** [comment]
this is my data format
```
311198,20170201060532,3430,13100004681,13100059535,202,70,7,3,20170203070802,20170202190644,1,2,5,4,8,3,0,4,8,3
481162,20170201085609,7454,13100000791,13100072598,446,42,4,8,20170203220037,20170202170721,0,5,9,3,3,6,9,8,0,2
965094,20170201020402,7306,13100067880,13100089379,253,69,7,8,20170203235528,20170203040419,3,2,2,3,8,8,9,9,2,3
279839,20170201073616,4850,13100017014,13100068760,967,70,1,2,20170204082541,20170202070411,3,6,5,7,5,0,4,3,7,6
511575,20170201072226,8691,13100005170,13100083748,853,35,0,0,20170203203134,20170203120650,3,8,3,5,2,5,8,8,7,6
750991,20170201063545,8566,13100073134,13100055349,23,44,2,6,20170203145727,20170202083750,3,6,5,1,6,2,6,0,1,0
772791,20170201042951,7813,13100011218,13100039468,270,49,9,0,20170203044438,20170204043105,9,8,4,9,6,4,4,7,3,0
996303,20170201055745,9468,13100073450,13100057450,643,55,2,7,20170203084717,20170203055341,3,9,3,6,4,5,2,9,1,7
```

**Comment by feloxx** [comment]
kafka to hdfs 
Whether to support text format?

**Comment by codenamelxl** [comment]
You have to formatted your data to KafkaAvroSerializer format when putting it into kafka.
It's mean that the data into your kafka muse be in the form:
MAGICBYTE(1byte)|Schema_ID(4byte)|Avro blob

**Comment by cricket007** [comment]
#283 added text support, so I feel this should be closed 

You're not using Avro, hence the error. Avro is the default format type for HDFS Connect

**Comment by kkonstantine** [comment]
Avro is the default format for the HDFS connector and as mentioned this doesn't match the imported data. Closing here but feel free to reopen with more details if this is not a data issue.
