### ISSUE TITLE
Throughput reduction on Avro schema evolution

### ISSUE THREAD

**Issue by dhamilton** [confluentinc/kafka-connect-hdfs#211]
We have been noticing drastic reductions in connector throughput whenever our Avro schemas evolves. We are using the Confluent schema registry. This throughput reduction lasts for several hours before finally clearing up, leading to a substantial lag for this period. I am wondering if there is anything we can do to avoid such issues when we update schemas in the future?
    
This is what I believe is happening:
    
- The avro producer application is running on multiple instances (4 or more). They are restarted in a rolling fashion, switching from producing schema version 1 before the restart to schema version 2 afterward.
- While the rolling restart is occurring, data on schema version 1 and schema version 2 is simultaneously being written to the topic depending on each producer's application version.
- The Kafka connector has to close the current avro file for a partition and ship it whenever it detects a schema change, which is happening several times due to the rolling nature of the schema update deployment and the mixture of message versions being written during this time. This process causes the overall consumer throughput to plummet.
    
Am I reasoning correctly about what we’re observing here? Is there any way to avoid this when we change schemas (short of stopping all instances of the service and bringing them up together on the new schema version)?
    
Thanks

**Comment by rhauch** [comment]
What you're describing does sound like the correct behavior when the `schema.compatibiility` connector configuration property is set to `NONE`, which is the default. This setting means that each file written to HDFS has the proper schema. When the connector observes a schema change in data, it commits the current set of files for the affected topic partitions and writes the data with the new schema in new files.

While you were performing the rolling upgrade of your producers, there would be a mixture of events with both old and new schemas. If a single HDFS sink connector task was seeing a mixture of events with old and new schemas and was configured with `schema.compatibility=NONE`, the connector would flush the file _every time it saw a change in schema_. For example, if we use 1 and 2 suffixes to signify the schema version and the connector sees events like `e1, e2, e1, e2, e2, e1, e1, e2`, the connector would have written them into files like this: `[e1], [e2], [e1], [e2, e2], [e1, e1], [e2]` (where the square brackets denote separate files).

Have you considered other schema compatibility settings? If your new schema is backward compatible and you set `schema.compatibility=BACKWARD`, then the connector can use the latest version of the schema that it sees. It will flush the current file when it sees a _new schema_, but after that it will always use the new schema, even if it encounters an event with an older schema. For example, if we use 1 and 2 suffixes to signify the schema version and the connector sees events like `e1, e2, e1, e2, e2, e1, e1, e2`, the connector would have written them into files like this: `[e1], [e2, e2, e2, e2, e2, e2, e2]`.

There is also the FORWARD schema compatibility setting, which is similar to BACKWARD except it uses the older schema rather than the new one. Given the same example, the files would be written like this: `[e1, e1, e1, e1, e1, e1, e1, e1]`.

Finally, there is the FULL schema compatibility setting, which works similarly to BACKWARD as long as your schemas are both backward and forward compatible.

The [HDFS documentation (last line)](http://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/index.html) more detail about the schema evolution and compatibility mechanism.

Hope this helps explain what you're seeing.

P.S, questions like this are probably best sent to the [discussion group](https://groups.google.com/forum/#!forum/confluent-platform), which is listed at the bottom of [Confluent's website](https://confluent.io) under "Resources".

**Comment by dhamilton** [comment]
Thank you, I wasn't aware of the discussion group. I'll direct questions like this there from now on.

I'll try setting the schema compatibility setting to BACKWARD which is what we've set on our schema registry instance and see if that helps. Thanks for your help.

**Comment by dhamilton** [comment]
Hi, sorry to circle back here, let me know if I should take this to the discussion board. We've tried setting schema.compatibility to BACKWARD however the connectors are often dying with WakeupExceptions even in the absence of a schema change. This is particularly odd since our consumer settings are consumer.session.timeout.ms=300000 and consumer.max.poll.records=50. Is there anything we are overlooking that could be causing this in the backward compatibility mode?


[2017-07-21 15:42:05,505] ERROR Commit of WorkerSinkTask{id=rtb_auction_raw_s3_v2-3} offsets threw an unexpected exception:  (org.apache.kafka.connect.runtime.WorkerSinkTask:204)
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the
 time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You ca
n address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:698)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:577)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommitSync(WorkerSinkTask.java:255)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommitSync(WorkerSinkTask.java:260)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommit(WorkerSinkTask.java:274)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:348)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-07-21 15:42:05,505] ERROR Task rtb_auction_raw_s3_v2-3 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.common.errors.WakeupException
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:411)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:239)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:188)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:578)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommitSync(WorkerSinkTask.java:255)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.doCommit(WorkerSinkTask.java:274)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:348)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:480)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-07-21 15:42:05,506] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)

**Comment by ewencp** [comment]
@dhamilton It looks like this exception is happening when the task is shutting down. Are there any messages earlier in the log indicating that it is shutting down? It sounds like your current problem doesn't have to do with the compatibility change, it looks more like you may be repeatedly rebalancing.

**Comment by levzem** [comment]
closing but feel free to reopen if you are still having issues
