### ISSUE TITLE
Confusion of fields with multiple connectors that are using FieldPartitioner

### ISSUE THREAD

**Issue by talnicolas** [confluentinc/kafka-connect-hdfs#216]
Hi,

I'm having a problem with my Kafka Connect HDFS setup due to some kind of confusion regarding the field used with the FieldPartitioner class.

I have two connectors:

- Topic topic_a with partition.field.name=serverdateid
- Topic topic_b with partition.field.name=transactionid

When those two are in RUNNING mode at the same time, I get the following error:

```
[2017-07-26 02:11:24,590] ERROR Exception on topic partition topic_b:  (io.confluent.connect.hdfs.TopicPartitionWriter:324)
org.apache.kafka.connect.errors.DataException: serverdateid is not a valid field name
        at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:253)
        at org.apache.kafka.connect.data.Struct.get(Struct.java:75)
        at io.confluent.connect.hdfs.partitioner.FieldPartitioner.encodePartition(FieldPartitioner.java:50)
        at io.confluent.connect.hdfs.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:533)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:294)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:234)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:103)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```
Instead of using its own partition field name it seems to only consider the one of topic_a.

(confluent platform 3.2)

**Comment by ewencp** [comment]
Can you share your connector configurations? The two configurations should be handled independently, so this definitely looks like strange behavior.

**Comment by talnicolas** [comment]
Sure. For now I worked around the problem by implementing Custom partitioner for each topic. Here are my configurations at the time:

**Connector A**:
```
"config": { 
    "connector.class":"HdfsSinkConnector", 
    "tasks.max": 2, 
    "hadoop.conf.dir":"/etc/hadoop/conf", 
    "hdfs.url":"/", 
    "flush.size": 5000, 
    "rotate.interval.ms": 30000, 
    "topics.dir": "/some/hdfs/path", 
    "logs.dir": "/some/hdfs/path/logs", 
    "hdfs.authentication.kerberos": true, 
    "connect.hdfs.principal": "some_user", 
    "connect.hdfs.keytab": "some_keytab",  
    "hdfs.namenode.principal": "hdfs/some_principal", 
    "hdfs.url": "hdfs://some_hdfs/",
    "hive.integration": true, 
    "hive.metastore.uris": "thrift://some_thrift", 
    "hive.conf.dir": "/etc/hive/conf", 
    "hive.database": "some_database", 
    "partitioner.class": "io.confluent.connect.hdfs.partitioner.FieldPartitioner",
    "partition.field.name": "serverdateid",
    "schema.compatibility": "BACKWARD",
    "topics": "topic_a"
  }
```
**Connector B**:
```
"config": { 
    "connector.class":"HdfsSinkConnector", 
    "tasks.max": 2, 
    "hadoop.conf.dir":"/etc/hadoop/conf", 
    "hdfs.url":"/", 
    "flush.size": 5000, 
    "rotate.interval.ms": 30000, 
    "topics.dir": "/some/hdfs/path_b", 
    "logs.dir": "/some/hdfs/path_b/logs", 
    "hdfs.authentication.kerberos": true, 
    "connect.hdfs.principal": "some_user", 
    "connect.hdfs.keytab": "some_keytab",  
    "hdfs.namenode.principal": "hdfs/some_principal", 
    "hdfs.url": "hdfs://some_hdfs/",
    "hive.integration": true, 
    "hive.metastore.uris": "thrift://some_thrift", 
    "hive.conf.dir": "/etc/hive/conf", 
    "hive.database": "some_database", 
    "partitioner.class": "io.confluent.connect.hdfs.partitioner.FieldPartitioner",
    "partition.field.name": "transactiondateid",
    "schema.compatibility": "BACKWARD",
    "topics": "topic_b"
  }
```

**Comment by ewencp** [comment]
Ouch, this is a nasty bug -- https://github.com/confluentinc/kafka-connect-hdfs/blob/3.3.x/src/main/java/io/confluent/connect/hdfs/partitioner/FieldPartitioner.java#L35 is the issue. It's `static` but clearly shouldn't be.

This is actually fixed already in later branches, the code has been refactored to use some common classes https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/partitioner/FieldPartitioner.java#L21 and the base class it now uses has the correct implementation https://github.com/confluentinc/kafka-connect-storage-common/blob/master/partitioner/src/main/java/io/confluent/connect/storage/partitioner/FieldPartitioner.java#L34

**Comment by talnicolas** [comment]
Cool, nice to see it has already been taken care of. In what release should we expect this change to be present?

**Comment by levzem** [comment]
closing as this was fixed as mentioned above
