### ISSUE TITLE
Migration from Camus - Handling RecordTime within messages

### ISSUE THREAD

**Issue by cricket007** [confluentinc/kafka-connect-hdfs#229]
Is there some documentation that describes the migration from Camus to Kafka Connect HDFS that preserves the `header.time` partitioning when using the `TimeBasedPartitioner`? 

Specifically, in Camus, [there is this section of code](https://github.com/confluentinc/camus/blob/master/camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/KafkaAvroMessageDecoder.java#L139) that extracts the timestamp if it exists, otherwise use the "wall clock". The majority of our Avro messages have this `header.time` field, and when testing a few topics, it'll dump our 7 day old data sitting at the earliest offsets into the current timestamp that KafkaConnect runs. Obviously this isn't ideal when we have time based events that people are wanting to do queries in Hive/Spark based on the generated hourly partitions.  

```java
    @Override
    public long getTimestamp() {
      Record header = (Record) super.getRecord().get("header");

      if (header != null && header.get("time") != null) {
        return (Long) header.get("time");
      } else if (super.getRecord().get("timestamp") != null) {
        return (Long) super.getRecord().get("timestamp");
      } else {
        return System.currentTimeMillis();
      }
    }
  }
```

As far as what I tried, here is the relevant section of the Connector config

```json
    "partitioner.class": "io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner",
    "_comment": "====== Hourly partitions with 15 minute dumps if flush size not reached ======",
    "partition.duration.ms": 3600000,
    "rotate.interval.ms": 900000,
    "rotate.schedule.interval.ms": 900000,
    "_comment": "====== Set the 'env=' partition for the appropriate Kafka cluster ======",
    "path.format": "'env=stage/date_hour='YYYYMMdd-HHmm",
    "_comment": "====== Extract the record timestamp ======",
    "timestamp.extractor" : "Record",
    "locale": "en",
    "timezone": "America/Chicago",
```

And this actually gives me a NullPointerException...  

```java
[2017-09-17 10:11:09,289] (pool-1-thread-5)  INFO - org.apache.kafka.clients.consumer.internals.AbstractCoordinator - (Re-)joining group connect-kafkaconnect-hdfs-laptop
[2017-09-17 10:11:09,313] (pool-1-thread-6)  INFO - io.confluent.connect.hdfs.TopicPartitionWriter - Started recovery for topic partition topicName.global-0
[2017-09-17 10:11:09,349] (pool-1-thread-6)  INFO - io.confluent.connect.hdfs.TopicPartitionWriter - Finished recovery for topic partition topicName.global-0
[2017-09-17 10:11:09,408] (pool-1-thread-6)  INFO - org.apache.kafka.clients.consumer.internals.Fetcher - Fetch offset 0 is out of range for partition topicName.global-0, resetting offset
[2017-09-17 10:11:09,676] (pool-1-thread-6) ERROR - org.apache.kafka.connect.runtime.WorkerSinkTask - Task kafkaconnect-hdfs-laptop threw an uncaught and unrecoverable exception
java.lang.NullPointerException
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:211)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:103)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-09-17 10:11:09,676] (pool-1-thread-6) ERROR - org.apache.kafka.connect.runtime.WorkerSinkTask - Task is being killed and will not recover until manually restarted
```

I have tested other topics without the timestamp extractor, and it is working fine, just not extracting the timestamp and placing the correct partition, as mentioned. 

I also tried `"timestamp.extractor" : "RecordField"` with `"timestamp.field" = "header.time"`, and that gives a StackOverflowError within the AvroParser, so maybe the extractor doesn't like the `header.time` value? I haven't had time too much to debug that... (I have overwrote my config and lost the logs, but I can try to get that again if someone really wants it). 

**So**, if anyone could just provide some pointers, that would be appreciated!

**Comment by cricket007** [comment]
Closing since #172 is working for me.
