### ISSUE TITLE
HDFS connector fails with thumbstone message in compacted topic

### ISSUE THREAD

**Issue by patrikni** [confluentinc/kafka-connect-hdfs#239]
Hi,
I tried to process compacted topic with thumbstone messages (value and schema is null). The connector fails with NullPointerException (no schema in processed record). I added some log messages to the code to find out cause of the failure. 
The exception:
2017-09-29 13:41:05,211 ERROR [pool-1-thread-8] Task sbd-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
        at io.confluent.connect.hdfs.schema.SchemaUtils.shouldChangeSchema(SchemaUtils.java:46)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:282)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:234)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:103)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-09-29 13:41:05,227 ERROR [pool-1-thread-8] Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask)

I tried to ignore thumstone messages in TopicPartitionWriter in buffer method
public void buffer(SinkRecord sinkRecord) {
	  if(sinkRecord.value()!=null) {
		  buffer.add(sinkRecord);
	  } else {
		  if(log.isDebugEnabled()) {
			  log.debug("Topic {} thumbstone message with offset {} has been ignored. value==null:{}, schema==null:{} ",
					  tp, sinkRecord.kafkaOffset(), sinkRecord.value()==null, sinkRecord.valueSchema()==null);
		  }
	  }
  }
Is there any better solution how to fix it?

**Comment by yuancheng-p** [comment]
Hi @patrikni , I encountered the same issue.  I think the hdfs connector should ignore the null value messages (as there's nothing to write to hdfs), instead of crashing by with a NullPointerException.

For the moment being, my solution is to create a custom transformer to skip those messages before the fix is done in the HDFS connector.

**Comment by patrikni** [comment]
Hi @yuancheng-p thank you for your workaround proposal. My current connector version is 3.2.1 so I can`t use it now. I have already added the mentioned condition to ignore the thumbstone message. 
I am curious about the new connector transformation feature and I hope we will migrate soon to be able to use it.

**Comment by cyrusv** [comment]
The best way to handle these is with an SMT that will filter or throw an error and put them in DLQ

**Comment by levzem** [comment]
closing as an SMT will resolve this issue
