### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.avro.Schema.getLogicalType()Lorg/apache/avro/LogicalType

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/kafka-connect-hdfs#261]
It's regression bug in confluent 4.0.0.

Probably connected with this commit:
https://github.com/confluentinc/kafka-connect-storage-common/commit/b54309f2cd76201a621368fea0846994c98ff900

HDFS sink failed with following exception.
I think problem is we have 2 different version of Avro in classpath.
One in avro-1.8.2.jar, second one in hive-exec.

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.avro.Schema.getLogicalType()Lorg/apache/avro/LogicalType;
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:178)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:130)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:227)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:124)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:115)
	at org.apache.parquet.avro.AvroParquetWriter.writeSupport(AvroParquetWriter.java:144)
	at org.apache.parquet.avro.AvroParquetWriter.<init>(AvroParquetWriter.java:106)
	at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:68)
	at io.confluent.connect.hdfs.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:635)
	at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:379)
	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
	at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	... 10 more
```

CC: @kkonstantine

**Comment by maver1ck** [comment]
Way to reproduce.
1) Create table in MySQL with timestamp column
```
CREATE TABLE `test_timestamp` (
	`id` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```
2) Use jdbc and hdfs connectors (with hive integration) to migrate data to hadoop.
3) Schema of this table in schema registry (look at logical type)
```
{
  "type": "record",
  "name": "test_timestamp",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "int"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "updated_at",
      "type": {
        "type": "long",
        "connect.version": 1,
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "logicalType": "timestamp-millis"
      }
    }
  ],
  "connect.name": "test_timestamp"
}
```

**Comment by maver1ck** [comment]
And configs:
JDBC Source
```
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "timestamp.column.name": "updated_at",
  "validate.non.null": "false",
  "tasks.max": "1",
  "table.whitelist": "test_timestamp",
  "mode": "timestamp",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "topic.prefix": "test_source_",
  "name": "test_source_test_timestamp",
  "connection.url": "jdbc:mysql://localhost:3306/test",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "http://localhost:8081"
}
```
HDFS Sink
```
{
  "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
  "hadoop.conf.dir": "/etc/hadoop/conf",
  "flush.size": "1",
  "schema.compatibility": "FULL",
  "topics": "test_source_test_timestamp",
  "timezone": "UTC",
  "hdfs.url": "hdfs://hdfstest/tmp/test_dest",
  "hive.database": "test_dest",
  "rotate.interval.ms": "3600000",
  "hive.metastore.uris": "thrift://amb2.service.consul:9083",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "hive.integration": "true",
  "format.class": "io.confluent.connect.hdfs.avro.AvroFormat",
  "name": "hdfs_sink_test_dest_xxx",
  "hive.conf.dir": "/etc/hive/conf",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "storage.class": "io.confluent.connect.hdfs.storage.HdfsStorage",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "http://localhost:8081",
  "rotate.schedule.interval.ms": "3600000"
}
```

**Comment by maver1ck** [comment]
Workaround:
I removed org.apache.avro.* files from hive-exec jar and add avro-mapred to classpath.
It worked.

**Comment by kkonstantine** [comment]
Since `hive-exec` includes several packages with it, this is potentially an issue due to a conflict in all previous versions. However it wasn't surfaced as long as the dependencies were added in a certain order in the classpath. 

The PR here is aiming to resolve this: https://github.com/confluentinc/kafka-connect-storage-common/pull/50

A potentially better workaround than removing packages from within `hive-exec` jar is to replace `hive-exec` jar with [hive-exec-core](https://repo1.maven.org/maven2/org/apache/hive/hive-exec/1.2.2/hive-exec-1.2.2-core.jar) and also add the required artifacts for kryo, commons-lang3 and avro-mapred same as the PR above practically does.

**Comment by jmkent** [comment]
Is there any timeline on an actual 4.0.1 release being cut to resolve this?  The fix is in master, and has been since early December.

**Comment by amalow** [comment]
Any updates on a fix being released for this?

**Comment by pederpansen** [comment]
Does anyone have a nightly/snapshot JAR of version 4.0.1? I was trying to build a development version myself like @maver1ck suggested, but I am lost building 10+ other dependent repositories.

**Comment by sruthinakkella** [comment]
I am facing the same issue with Confluent v4.0. Could someone me with the work around

**Comment by jmkent** [comment]
Plus side, tags have been cut and rapidly going through RCs, so it looks like this is incoming shortly: https://github.com/confluentinc/kafka-connect-hdfs/releases

**Comment by skysaeed** [comment]
downgrade to Apache Confluent version 3.3.1 solved the problem!

**Comment by kkonstantine** [comment]
This issue has been fixed in recent regular and bugfix releases
