### ISSUE TITLE
java.lang.RuntimeException: org.apache.kafka.connect.errors.SchemaProjectorException: Schema version required for BACKWARD compatibility

### ISSUE THREAD

**Issue by nagukothapalli** [confluentinc/kafka-connect-hdfs#263]
Getting below exception when i integrate with hive with own converter classes

```
hive.integration=true
hive.metastore.uris=thrift://localhost:9083
schema.compatibility=BACKWARD

partitioner.class=io.confluent.connect.hdfs.partitioner.HourlyPartitioner
locale=en-us
timezone=UTC
```
``` java.lang.RuntimeException: org.apache.kafka.connect.errors.SchemaProjectorException: Schema version required for BACKWARD compatibility
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:292)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:234)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:91)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:370)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.SchemaProjectorException: Schema version required for BACKWARD compatibility
        at io.confluent.connect.hdfs.schema.SchemaUtils.shouldChangeSchema(SchemaUtils.java:42)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:251)
```

**Comment by cricket007** [comment]
> with own converter classes

> `SchemaProjectorException: Schema version required`

Sounds like your Avro data doesn't have a Schema ID. [Exception here](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/schema/SchemaUtils.java#L46)

**Comment by nagukothapalli** [comment]
I am serializing using with AvroData.java ( one of the confluent class)

This means do i need to include schema.version  in each  record ? 
Is that schema version should be schema version in schema registry

**Comment by cricket007** [comment]
Can you please add your producer code?

**Comment by cricket007** [comment]
Is this still relevant? 

If so, to follow up on 
> I am serializing using with AvroData

You shouldn't be using this in your producer code. Please use this property in the producer `"value.serializer", KafkaAvroSerializer.class`

**Comment by kkonstantine** [comment]
Since you are writing your own `Converter` you might find useful to check the code for the `AvroConverter` here: 

https://github.com/confluentinc/schema-registry/blob/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java

It's also using `AvroData`. 
Closing since this is ticket does not describe an issue with the Connector currently.
