### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

### ISSUE THREAD

**Issue by wanygan83** [confluentinc/kafka-connect-hdfs#268]
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:647)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:654)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:386)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.error(ParquetFileWriter.java:182)
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.startBlock(ParquetFileWriter.java:174)
        at org.apache.parquet.hadoop.ParquetFileWriter.startBlock(ParquetFileWriter.java:284)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:166)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109)
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:302)
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:95)
        ... 16 more

version:4.0.0

**Comment by Minutis** [comment]
Having the same issue. Any updates on this?

**Comment by pdambrauskas** [comment]
Same here. Happens randomly after worker rebalance/kafka connect restart. Any updates?
@ewencp I see you have significantly contributed to `TopicPartitionWriter`, I guess it is related to this class. Any ideas what can be the cause of this preblem?

We are using kafka-connect-hdfs 4.0.0.

**Comment by ravindratcs** [comment]
We are also facing the same issue. Is these any solution to this error. It look like common issue as reported by multiple users.

**Comment by rupeshmore85** [comment]
Receiving the same error for Parquet file format.

**Comment by wanygan83** [comment]
I modify hadoop write/read socket timeout param
