### ISSUE TITLE
 java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig

### ISSUE THREAD

**Issue by unilama** [confluentinc/kafka-connect-hdfs#273]
Hi

During creation of HdfsSinkConnector via REST API using this JSON request:

```
 {
 "name": "hdfs-sink-dev", 
 "config": {
 		"connector.class": "HdfsSink",
 		"flush.size":"200",
 		"hdfs.url": "hdfs://NN-host-name:8020",
 		"topics": "topic1,topic2,topic3"
   }
}
```

Result is Error Code 500 and in log I can find trace: 

```
2018-01-11 09:23:39,792 INFO   10.8.1.182 - - [11/Jan/2018:09:23:39 +0000] "POST /connectors HTTP/1.1" 500 294  115   [org.apache.kafka.connect.runtime.rest.RestServer]
2018-01-11 09:23:39,794 WARN   /connectors   [org.eclipse.jetty.server.HttpChannel]
javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	... 10 more
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:54)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.confluent.connect.hdfs.HdfsSinkConnector.config(HdfsSinkConnector.java:78)
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:132)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:265)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:528)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:525)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:261)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.ClassNotFoundException: io.confluent.connect.storage.StorageSinkConnectorConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
2018-01-11 09:23:39,796 WARN   Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig   [org.eclipse.jetty.server.HttpChannel]
```
Confluent platform in version 4.0.0 is installed using RPM packages, worker is started using 

```
/bin/connect-distributed config.properties
```

config.properties file: 

```
config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
group.id=connect
bootstrap.servers=kafka-broker-1:9092,kafka-broker-2:9092
offset.flush.interval.ms=60000
offset.flush.timeout.ms=5000
shutdown.timeout=10000
key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
key.converter.schema.registry.url=http://schema-registry-1:8081/,http://schema-registry-2:8081/
value.converter.schema.registry.url=http://schema-registry-1:8081/,http://schema-registry-2:8081/
status.storage.topic=connect-status
config.storage.replication.factor=2
offset.storage.replication.factor=2
status.storage.replication.factor=2
plugin.path=/usr/share/java/kafka-connect-hdfs,/usr/share/java/kafka-connect-debezium/debezium-mysql-0.7.1
hadoop.conf.dir=/etc/hadoop/conf
```

On the same distributed cluster using Debezium MySQL Connect  plugin without any problems.

For reference result of: http://connect-worker-1:8083/connector-plugins/

```
[
	{
		"class": "io.confluent.connect.hdfs.HdfsSinkConnector",
		"type": "sink",
		"version": "4.0.0"
	},
	{
		"class": "io.confluent.connect.hdfs.tools.SchemaSourceConnector",
		"type": "source",
		"version": "1.0.0-cp1"
	},
	{
		"class": "io.debezium.connector.mysql.MySqlConnector",
		"type": "source",
		"version": "0.7.1"
	},
	{
		"class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
		"type": "sink",
		"version": "1.0.0-cp1"
	},
	{
		"class": "org.apache.kafka.connect.file.FileStreamSourceConnector",
		"type": "source",
		"version": "1.0.0-cp1"
	}
]
```

**Comment by kkonstantine** [comment]
Your `plugin.path` is wrong. It should probably be `plugin.path=/usr/share/java`. 

This way all connectors with their dependencies will be loaded in isolation, including debezium. 

`plugin.path` supports nesting of directories. However the property needs to be set to a top-level directory that contains directories with the connector jars and their dependencies or/and connector uber-jars. 

Schematically, this should be: 

```
/usr/share/java/
            kafka-connect-hdfs/
                        storage-common -> ../kafka-connect-storage-common               
            kafka-connect-storage-common/
            kafka-connect-debezium/
```
etc...

**Comment by unilama** [comment]
Thx for suggestion but only exception is changed:

`2018-01-12 16:43:38,623 INFO   10.8.1.182 - - [12/Jan/2018:16:43:38 +0000] "POST /connectors HTTP/1.1" 500 294  9   [org.apache.kafka.connect.runtime.rest.RestServer]
2018-01-12 16:43:38,623 WARN   /connectors   [org.eclipse.jetty.server.HttpChannel]
javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/hdfs/HdfsSinkConnectorConfig
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/hdfs/HdfsSinkConnectorConfig
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	... 10 more
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/hdfs/HdfsSinkConnectorConfig
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: io/confluent/connect/hdfs/HdfsSinkConnectorConfig
	at io.confluent.connect.hdfs.HdfsSinkConnector.config(HdfsSinkConnector.java:78)
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:132)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:265)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:528)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:525)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:261)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
2018-01-12 16:43:38,633 WARN   Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: io/confluent/connect/hdfs/HdfsSinkConnectorConfig   [org.eclipse.jetty.server.HttpChannel]`


Actually now it cannot found class that is in the same jar since:
`io.confluent.connect.hdfs.HdfsSinkConnector` and missing class `io/confluent/connect/hdfs/HdfsSinkConnectorConfig` are located in same jar:
`/usr/share/java/kafka-connect-hdfs/kafka-connect-hdfs-4.0.0.jar`

**Comment by AlexisSellier** [comment]
Same problem here but the class is present in the jar
```
jar tf kafka-connect-hdfs-4.0.0.jar | grep io/confluent/connect/hdfs/HdfsSinkConnectorConfig
io/confluent/connect/hdfs/HdfsSinkConnectorConfig$BooleanParentRecommender.class
io/confluent/connect/hdfs/HdfsSinkConnectorConfig.class

```

**Comment by kkonstantine** [comment]
Is there a relative symbolic link under `share/java/kafka-connect-hdfs` to `../kafka-connect-storage-common` which should basically be pointing to `share/java/kafka-connect-storage-common`?

Again, is your `plugin.path` set to `/usr/share/java` at least for the hdfs connector? It should not directly point to `/usr/share/java/kafka-connect-hdfs` because it will misinterpret the dependencies of hdfs connector for uber-jars of connect plugins. 

I'm able to load the hdfs connector with mongo and mysql debezium connectors without classloading issues if, for instance, I extract the debezium connectors under `share/java` in confluent platform's homedir.

**Comment by unilama** [comment]
Ok, it works under this conditions:
* plugin path need to be wide: ```plugin.path=/usr/share/java/```
* symlink need to be created:
```
$ ls -lha /usr/share/java/kafka-connect-hdfs
total 3.1M
drwxr-xr-x   2 root root 8.0K Jan 17 12:03 .
drwxr-xr-x. 13 root root 4.0K Jan  4 14:25 ..
-rw-r--r--   1 root root  21K Nov 21 19:28 common-utils-4.0.0.jar
-rw-r--r--   1 root root 209K Nov 21 19:28 jline-2.12.1.jar
-rw-r--r--   1 root root 122K Nov 21 19:28 kafka-connect-hdfs-4.0.0.jar
lrwxrwxrwx   1 root root   44 Jan 17 12:03 kafka-connect-storage-common -> /usr/share/java/kafka-connect-storage-common
-rw-r--r--   1 root root 479K Nov 21 19:28 log4j-1.2.17.jar
-rw-r--r--   1 root root 1.3M Nov 21 19:28 netty-3.10.5.Final.jar
-rw-r--r--   1 root root  41K Nov 21 19:28 slf4j-api-1.7.25.jar
-rw-r--r--   1 root root  74K Nov 21 19:28 zkclient-0.10.jar
-rw-r--r--   1 root root 851K Nov 21 19:28 zookeeper-3.4.10.jar
```

Still need to be addressed in packaging at least RPM version, this symlink should be defined in package, where can I create merge request to fix it

Another issue that should be addressed that endpoint should return JSON with error code instead HTTP 500 Page

**Comment by kkonstantine** [comment]
Regarding rpm packaging: 

Listing the contents of the connector's rpm shows that the symlink is included in the archive and it's a relative one: 

`$ rpm -qlpv ./confluent-kafka-connect-hdfs-4.0.0-1.noarch.rpm `

```
... (lots of license files) ...
drwxr-xr-x    2 root    root                0 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs
-rw-r--r--    1 root    root            20846 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/common-utils-4.0.0.jar
-rw-r--r--    1 root    root           213911 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/jline-2.12.1.jar
-rw-r--r--    1 root    root           124490 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/kafka-connect-hdfs-4.0.0.jar
-rw-r--r--    1 root    root           489884 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/log4j-1.2.17.jar
-rw-r--r--    1 root    root          1330394 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/netty-3.10.5.Final.jar
-rw-r--r--    1 root    root            41203 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/slf4j-api-1.7.25.jar
lrwxrwxrwx    1 root    root               31 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/storage-common -> ../kafka-connect-storage-common
-rw-r--r--    1 root    root            74798 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/zkclient-0.10.jar
-rw-r--r--    1 root    root           871369 Nov 21 11:28 /usr/share/java/kafka-connect-hdfs/zookeeper-3.4.10.jar
```

Mentioning a few details of your setup might help us track down an issue with packaging, if indeed there is one. For instance: 
- Flavor and version of Linux
- Version of rpm command
- How you install the connector (exact rpm command - individual installation of the package or installation as part of installing the complete confluent platform package?)
- Version of the connector
- Version of Kafka Connect (there was an issue with relative symlinks in `3.3.0`. Fixed in `3.3.1` and `4.0.0`)

**Comment by kkonstantine** [comment]
Indeed packaging was not distinguishing between pre v4 and post v4 branches for `rpm` and `debian` packages, which when the refactoring on top of https://github.com/confluentinc/kafka-connect-storage-common happened. 

Fixed here: https://github.com/confluentinc/kafka-connect-hdfs/pull/274 and here: https://github.com/confluentinc/kafka-connect-hdfs/pull/275

Thanks for mentioning!

**Comment by dbranscombe** [comment]
Sorry to post on closed thread, but wondering if there could be a similar issue with trying to use the JdbcSourceConnector. I'm not sure why its looking for a SinkConnector when trying to use a SourceConnector, but I get same error:

ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone) java.lang.NoClassDefFoundError: io/confluent/connect/storage/StorageSinkConnectorConfig

NOTE: I have edited the plugin path as noted ( plugin.path=/kafkaconnect/confluent-oss-4.1.1-2.11.tar/confluent-oss-4.1.1-2.11/confluent-4.1.1/share/java)

....and god help me, I'm running in windows.

![image](https://user-images.githubusercontent.com/852985/42544885-4bfb34ca-8469-11e8-9a21-f339e1b69d7d.png)
