### ISSUE TITLE
org.apache.hadoop.hive.serde2.avro.AvroSerdeException Invalid precision or scale for decimal type

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/kafka-connect-hdfs#279]
I'm using Kafka Connect v4.0.0.

I'm getting exception when reading table saved by Kafka Connect (both with Hive and Spark)
Spark:
```
18/01/29 09:39:49 ERROR Table: Unable to get field from serde: org.apache.hadoop.hive.serde2.avro.AvroSerDe
java.lang.RuntimeException: MetaException(message:org.apache.hadoop.hive.serde2.avro.AvroSerdeException Invalid precision or scale for decimal type)
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:278)
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializer(Table.java:258)
        at org.apache.hadoop.hive.ql.metadata.Table.getCols(Table.java:605)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getTableOption$1$$anonfun$apply$11.apply(HiveClientImpl.scala:365)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getTableOption$1$$anonfun$apply$11.apply(HiveClientImpl.scala:361)
        at scala.Option.map(Option.scala:146)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getTableOption$1.apply(HiveClientImpl.scala:361)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getTableOption$1.apply(HiveClientImpl.scala:359)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:279)
        at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:226)
        at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:225)
        at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:268)
        at org.apache.spark.sql.hive.client.HiveClientImpl.getTableOption(HiveClientImpl.scala:359)
        at org.apache.spark.sql.hive.client.HiveClient$class.getTable(HiveClient.scala:74)
        at org.apache.spark.sql.hive.client.HiveClientImpl.getTable(HiveClientImpl.scala:78)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable$1.apply(HiveExternalCatalog.scala:110)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable$1.apply(HiveExternalCatalog.scala:110)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
        at org.apache.spark.sql.hive.HiveExternalCatalog.org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable(HiveExternalCatalog.scala:109)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:620)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:620)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
        at org.apache.spark.sql.hive.HiveExternalCatalog.getTable(HiveExternalCatalog.scala:619)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:124)
        at org.apache.spark.sql.hive.HiveSessionCatalog.lookupRelation(HiveSessionCatalog.scala:70)
        at org.apache.spark.sql.DataFrameReader.table(DataFrameReader.scala:473)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)

```
Hive:
```
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.serde2.avro.AvroSerdeException Invalid precision or scale for decimal type
```

I created table (MySQL):
```
CREATE TABLE `test_columns` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`col_decimal` DECIMAL(8,2) NOT NULL,
	PRIMARY KEY (`id`)
)
```
Then I created two connectors:
JDBC
```
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "incrementing.column.name": "id",
  "transforms.createKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
  "schema.compatibility": "FULL",
  "tasks.max": "1",
  "transforms": "createKey,extractInt",
  "transforms.extractInt.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
  "timestamp.delay.interval.ms": "0",
  "table.whitelist": "test_columns",
  "mode": "incrementing",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "topic.prefix": "test_source_",
  "transforms.extractInt.field": "id",
  "transforms.createKey.fields": "id",
  "name": "test_source_test_columns",
  "connection.url": "jdbc:mysql://localhost:3306/test",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "http://localhost:8081"
}
```
And HDFS (writing to Avro):
```
{
  "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
  "hadoop.conf.dir": "/etc/hadoop/conf",
  "flush.size": "1",
  "schema.compatibility": "FULL",
  "topics": ",test_source_test_columns",
  "timezone": "UTC",
  "hdfs.url": "hdfs://hdfstest/tmp/avro/test_avro",
  "hive.database": "test_avro",
  "hive.metastore.uris": "thrift://localhost:9083",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "hive.integration": "true",
  "format.class": "io.confluent.connect.hdfs.avro.AvroFormat",
  "name": "hdfs_test_avro_common",
  "hive.conf.dir": "/etc/hive/conf",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "storage.class": "io.confluent.connect.hdfs.storage.HdfsStorage",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "http://localhost:8081",
  "rotate.schedule.interval.ms": "3600000"
}

```

Schema for this table in Schema registry:
```
{
  "type": "record",
  "name": "test_columns",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "col_decimal",
      "type": {
        "type": "bytes",
        "scale": 2,
        "precision": 64,
        "connect.version": 1,
        "connect.parameters": {
          "scale": "2"
        },
        "connect.name": "org.apache.kafka.connect.data.Decimal",
        "logicalType": "decimal"
      }
    }
  ],
  "connect.name": "test_columns"
}
```

**Comment by maver1ck** [comment]
The problem is with precision.
max precision for hive is 38.
https://github.com/apache/hive/blob/cb866e894bc5cf536ab3ba7b0e1542e8dbda7932/serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/HiveDecimalUtils.java#L42

**Comment by rhauch** [comment]
@maver1ck , I've also responded on [your Schema Registry PR](https://github.com/confluentinc/schema-registry/pull/726), but this doesn't really seem like an Avro problem and is actually more of an issue with the HDFS connector. Can you elaborate?

**Comment by Gordon-Wu1** [comment]
I also encountered this problem.
How did you solve it?
Thank you

**Comment by chickensoup** [comment]
I met the same issue. I checked the schema in schema registry and found the precision is 64. So the issue is at source connector side, i.e. the source connector put the wrong precision in schema registry. I'm looking into the source connector now.

**Comment by MrTrustworthy** [comment]
This issue also seems to happen in combination with Debezium, which often specifies 64 as precision even though the original column in the source table might actually have less precision. On the other hand, there are reasonable cases where you might have data with a precision of 64 and want to insert this into HIVE.

I'm trying to find out how exactly the error happens because I'm not sure why there are no safeguards against creating a table with a too-high precision in HIVE. For actually inserting values, there seem to be some measures to prevent going above the max precision of 38 like rounding up or inserting nulls (see https://cwiki.apache.org/confluence/download/attachments/27362075/Hive_Decimal_Precision_Scale_Support.pdf). 

Why a similar approach is not done for the table creation is somewhat confusing, and I'm wondering whether it might be a good idea to handle this in the HDFS connector. For example, clamping the precision of decimal columns to min(schema_registry_value, 38) and then letting HIVE deal with any rounding/adjusting of the inserted values. What's your take on that @rhauch ?

**Comment by maver1ck** [comment]
I think this issue was fixed.
