### ISSUE TITLE
Issue in connecting to Kerberized Hadoop

### ISSUE THREAD

**Issue by srijiths** [confluentinc/kafka-connect-hdfs#297]
I am connecting to Cloudera Kerberized Hadoop cluster. Below is my properties.

```
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=hdfs-topic
hdfs.url=/user/hdfs/iot
flush.size=3
hdfs.authentication.kerberos=true
connect.hdfs.principal=ubuntu/admin@EXAMPLE.COM
connect.hdfs.keytab=/home/ubuntu/ubuntu.keytab
hdfs.namenode.principal=hdfs/ip-XX-XX-XX-XX.ap-southeast-1.compute.internal@EXAMPLE.COM
kerberos.ticket.renew.period.ms=3600000

```

Getting an exception 

```
[2018-03-15 09:16:07,539] INFO Hadoop configuration directory  (io.confluent.connect.hdfs.DataWriter:93)
[2018-03-15 09:16:07,874] INFO Hadoop namenode principal: hdfs/ip-XX-XX-XX-XXX.ap-southeast-1.compute.internal@EXAMPLE.COM (io.confluent.connect.hdfs.DataWriter:124)
[2018-03-15 09:16:07,939] WARN Unable to load native-hadoop library for your platform... using builtin-java classes where applicable (org.apache.hadoop.util.NativeCodeLoader:62)
[2018-03-15 09:16:08,145] INFO Couldn't start HdfsSinkConnector: (io.confluent.connect.hdfs.HdfsSinkTask:84)
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: Login failure for ubuntu/admin@EXAMPLE.COM from keytab /home/ubuntu/ubuntu.keytab: javax.security.auth.login.LoginException: Unable to obtain password from user

        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:202)
        at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:76)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Login failure for ubuntu/admin@EXAMPLE.COM from keytab /home/ubuntu/ubuntu.keytab: javax.security.auth.login.LoginException: Unable to obtain password from user

        at org.apache.hadoop.security.UserGroupInformation.loginUserFromKeytab(UserGroupInformation.java:963)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:127)
        ... 10 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain password from user

        at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:897)
        at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760)
        at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromKeytab(UserGroupInformation.java:954)
        ... 11 more
[2018-03-15 09:16:08,150] INFO Shutting down HdfsSinkConnector. (io.confluent.connect.hdfs.HdfsSinkTask:85)
[2018-03-15 09:16:08,150] INFO Sink task WorkerSinkTask{id=hdfs-sink-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
[2018-03-15 09:16:08,317] INFO Discovered coordinator 10.0.1.24:9092 (id: 2147483646 rack: null) for group connect-hdfs-sink. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:597)
[2018-03-15 09:16:08,320] INFO Revoking previously assigned partitions [] for group connect-hdfs-sink (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:419)
[2018-03-15 09:16:08,320] INFO (Re-)joining group connect-hdfs-sink (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432)
[2018-03-15 09:16:08,334] INFO Successfully joined group connect-hdfs-sink with generation 3 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399)
[2018-03-15 09:16:08,337] INFO Setting newly assigned partitions [hdfs-topic-0] for group connect-hdfs-sink (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262)
[2018-03-15 09:16:17,235] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
java.lang.NullPointerException
        at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:121)
       at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:486)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:152)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2018-03-15 09:16:17,236] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)
^C[2018-03-15 09:16:20,103] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2018-03-15 09:16:20,106] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2018-03-15 09:16:20,107] INFO Stopped ServerConnector@50670c3b{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2018-03-15 09:16:20,124] INFO Stopped o.e.j.s.ServletContextHandler@46f983c2{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2018-03-15 09:16:20,127] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2018-03-15 09:16:20,127] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:76)
[2018-03-15 09:16:20,127] INFO Stopping task hdfs-sink-0 (org.apache.kafka.connect.runtime.Worker:447)
[2018-03-15 09:16:20,128] INFO Stopping connector hdfs-sink (org.apache.kafka.connect.runtime.Worker:301)
[2018-03-15 09:16:20,128] INFO Stopped connector hdfs-sink (org.apache.kafka.connect.runtime.Worker:317)
[2018-03-15 09:16:20,128] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:156)
[2018-03-15 09:16:20,128] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:67)
[2018-03-15 09:16:20,128] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:176)
[2018-03-15 09:16:20,129] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:86)
[2018-03-15 09:16:20,129] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)

```
We have tested kerberos commands to connect from remote machine using the specified keytab and principal and its able to connect. 

Thank You

**Comment by alexandrfox** [comment]
Are you sure that your keytab file is readable by the user that launches Connect instance?

**Comment by srijiths** [comment]
Connect instance is launched as root. Any preferable chmod for keytab file ?

**Comment by alexandrfox** [comment]
`400`, but it shouldn't be a problem for you if you launch Connect as root (which is less than ideal).

**Comment by srijiths** [comment]
I have tried in another Kerberized hadoop machine and getting a different exception.

```
[2018-03-23 04:57:44,049] ERROR Task hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
java.lang.IllegalArgumentException: Can't get Kerberos realm
        at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
        at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:276)
        at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:312)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:126)
        at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:76)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:84)
        at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
        ... 13 more
Caused by: KrbException: Cannot locate default realm
        at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
        ... 19 more
[2018-03-23 04:57:44,055] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)

```
Do i need to setup Kerberos client and set realm in the machine where Connector is running ? When i tried a normal Java program in the same machine as Hadoop , its able to connect. When trying from a remote machine these exceptions are coming.

**Comment by alexandrfox** [comment]
Yes, `/etc/krb5.conf` needs to be present on Connect machine as well as keytab file.

**Comment by srijiths** [comment]
Thank You @alexandrfox Let me try this option.

**Comment by srijiths** [comment]
@alexandrfox Thank You Very much. Its working. :)
