### ISSUE TITLE
Kafka-HDFS-Connector. Not able to write kafka message

### ISSUE THREAD

**Issue by N-NicK** [confluentinc/kafka-connect-hdfs#309]
Hi Team,
I have two Machine.
Machine A on which Confluent Kafka-HDFS Sink Connector is Running.
Machine B on which hadoop is installed.
I want to write kafka topic from machine A to machine B.
Please Help Me Out From This Problem.

**Comment by cricket007** [comment]
It would be useful for you to provide your connector configuration and any errors you're observing.

Also check your firewall and network availability between the Connect instances and the Hadoop Namenode and Datanodes

**Comment by N-NicK** [comment]
**Output When Loading the Connector:**
```
bin/confluent load hdfs-sink -d etc/kafka-connect-hdfs/quickstart-hdfs.properties
{
  "name": "hdfs-sink",
  "config": {
    "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
    "tasks.max": "1",
    "topics": "test_hdfs",
    "hdfs.url": "hdfs://hadoopnode:9000",
    "flush.size": "3",
    "name": "hdfs-sink"
  },
  "tasks": [
    {
      "connector": "hdfs-sink",
      "task": 0
    }
  ],
  "type": null
}
```

Logs:
**confluent log connect**
```

[2018-04-01 14:32:20,243] INFO Hadoop configuration directory  (io.confluent.connect.hdfs.DataWriter:123)
[2018-04-01 14:32:20,279] INFO Couldn't start HdfsSinkConnector: (io.confluent.connect.hdfs.HdfsSinkTask:89)
org.apache.kafka.connect.errors.ConnectException: java.net.ConnectException: Call From aragolinux01.sds.local/10.0.1.114 to hadoopnode:900
0 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/Conn
ectionRefused
        at io.confluent.connect.hdfs.storage.HdfsStorage.exists(HdfsStorage.java:109)
        at io.confluent.connect.hdfs.DataWriter.createDir(DataWriter.java:531)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:220)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
        at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:81)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:267)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call From aragolinux01.sds.local/10.0.1.114 to hadoopnode:9000 failed on connection exception: java.
net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
        at org.apache.hadoop.ipc.Client.call(Client.java:1479)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy46.getFileInfo(Unknown Source)

```
I am able to ping each other.

**Comment by cricket007** [comment]
I'm not familiar with what port 9000 is used for. 

But if `hadoopnode` is a HDFS namespace in an HA setup, see #288 . Otherwise, I suggest you try the namenode IP address, then move to the FQDN if that works.

**Comment by N-NicK** [comment]
I also tried with IP address in place of hadoopnode(hostname).
When both hadoop and Confluent Kafka-HDFS-Connector is running in same Machine it is working fine.

port 9000 is the port number of "hdfs.url": "hdfs://localhost:9000".

**Comment by cricket007** [comment]
My point was that [`8020` is the HDFS NameNode RPC port, by default](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml), not 9000. 

Also, I suspect either 

1. `hadoopnode.sds.local` is not resolvable by DNS
2. You need to have Hadoop listening on an external network address. For example, setup an external hdfs client and attempt a `hadoop fs -ls hdfs://hadoopode:9000/` to see if you can connect that way. 

I suspect this is a network misconfiguration, not a Kafka Connect problem.

**Comment by N-NicK** [comment]
Thanks, @cricket007 I am able to resolve the problem. Now I am able to write kafka topic data from machine A to machine B.
