### ISSUE TITLE
Please describe "store.url" parameter.

### ISSUE THREAD

**Issue by glarus089** [confluentinc/kafka-connect-hdfs#310]
So, in documentation on HDFS sink connector we have "The HDFS connection URL. This configuration has the format of hdfs:://hostname:port and specifies the HDFS to export data to. This property is deprecated and will be removed in future releases. Use store.url instead." Also in storage section we can see "store.url" parameter, wich described as " Store’s connection URL, if applicable. Type: string Default: null Importance: high". Is anywhere exists some example configuration of sink connector using this parameters? Can i use HttpFS urls? Can i use more than one url, and how connector will work in that case?

**Comment by cricket007** [comment]
`store.url` is designed to be the same option as `hdfs.url` but is now shared over multiple filesystems such as local FS, S3, Azure, and GCS.

HttpFS doesn't use the same protocols as the Namenode RPC, so I doubt it would work. 

Also setting multiple urls probably wouldn't work either, and if you needed that feature, it could be implemented instead using Hadoop ViewFS features

**Comment by NicolasDutronc** [comment]
Hello @cricket007 , I would like to write data from kafka to hive with an s3 backend. Your message suggests it should be possible with this connector but I can't make it work...
My config is: cp 5.0.0 in docker
My connector:
```
{
    "name": "hdfs-sink",
    "config": {
        "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
        "tasks.max": "1",
        "topics": "test_hive",
        "store.url": "http://minio:9000",
        "flush.size": "1",
        "format.class": "io.confluent.connect.hdfs.avro.AvroFormat",
        "hive.integration": "true",
        "hive.metastore.uris": "thrift://metastore:9083",
        "hive.conf.dir": "/opt/hive/conf",
        "hive.home": "/opt/hive",
        "hive.database": "test",
        "schema.compatibility": "FULL",
        "hadoop.conf.dir": "/opt/hadoop/etc",
        "hadoop.home": "/opt/hadoop"
    }
}
```
My issue:
```
[2018-11-12 15:02:08,500] INFO Couldn't start HdfsSinkConnector: (io.confluent.connect.hdfs.HdfsSinkTask)
org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:56)
	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:214)
	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
	at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:82)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:190)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:51)
	... 12 more
Caused by: java.io.IOException: No FileSystem for scheme: http
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2691)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:420)
	at io.confluent.connect.hdfs.storage.HdfsStorage.<init>(HdfsStorage.java:56)
	... 17 more
```

**Comment by cricket007** [comment]
An example of using Spark, which internally uses the Hadoop Filesystem APIs just like this connector, that writes data and uses the S3A protocol can be found in the Minio docs - https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md#write

As that page mentions, you might need to edit the classpath of the Connector to support some extra AWS/Minio SDK JAR packages

**Comment by NicolasDutronc** [comment]
@cricket007 thanks for your replies. When I use the s3 connector with Minio, it works fine with the `http` protocol. Anyway I just tried `s3a://` instead of `http://` and I still get the same error but now caused by:
```
Caused by: java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at io.confluent.connect.hdfs.storage.HdfsStorage.<init>(HdfsStorage.java:56)
	... 17 more
```
I wish I could use a more s3 like connector but I want to store data as hive tables, regardless of the storage backend.

**Comment by cricket007** [comment]
It's been on my personal backlog to see how to get the S3 Connector to support Hive. The relevant classes and methods are all available, just not setup.

In the meantime, I have seen people using S3 lambda triggers that'll fire off `ADD PARTITION` events to the metastore. https://aws.amazon.com/blogs/big-data/data-lake-ingestion-automatically-partition-hive-external-tables-with-aws/

Minio does support bucket events - https://blog.minio.io/lambda-computing-with-minio-and-kafka-de928897ccdf

Probably more code than what's really necessary here. 

The NPE is likely related to some missing hadoop-aws library, or `HdfsStorage.<init>(HdfsStorage.java:56)` is literally pulling a null value from the config somehow; someone would have to debug to figure out why that is

**Comment by NicolasDutronc** [comment]
I will try to add the jars.
Have you heard of [this project](https://github.com/Landoop/stream-reactor/tree/master/kafka-connect-hive) ?

**Comment by cricket007** [comment]
Yeah, I know of StreamReactor / Landoop Lenses, but that Hive one [isn't documented](https://docs.lenses.io/connectors/sink-connectors.html), so YMMV
