### ISSUE TITLE
Invalid Java object for schema type INT32: class java.lang.Integer for field: "null"

### ISSUE THREAD

**Issue by ramonsgh** [confluentinc/kafka-connect-hdfs#313]
Hi,

I am trying to use Confluent HDFS connector to upload data from our Kafka topics to HDFS in Avro format.

We are facing an issue when data type 'Datetime' involved:

[2018-04-09 17:16:15,008] ERROR WorkerSinkTask{id=hdfs-connect-2} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1527)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1410)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1290)
	at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1014)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:88)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:454)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type INT32: class java.lang.Integer for field: "null"
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:239)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:209)
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)
	... 16 more

The following is the content of schema registry for this topic:

{"subject":"hdfs-connect-value","version":27,"id":64,"schema":"{\"type\":\"record\",\"name\":\"production_plan\",\"fields\":[{\"name\":\"PP_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Actual_Bad_Items\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Actual_Bad_Quantity\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Actual_Down_Time\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Actual_End_Time\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"},\"default\":\"00:00:00\"},{\"name\":\"Actual_Good_Items\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Actual_Good_Quantity\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Actual_Repetitions\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Actual_Running_Time\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Actual_Start_Time\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"},\"default\":\"00:00:00\"},{\"name\":\"Adjusted_Quantity\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Alarm_Count\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Block_Number\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"BOM_Formulation_Id\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Comment_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Control_Type\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Entry_On\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"},\"default\":\"00:00:00\"},{\"name\":\"Extended_Info\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"Forecast_End_Date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"},\"default\":\"00:00:00\"},{\"name\":\"Forecast_Quantity\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Forecast_Start_Date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"},\"default\":\"00:00:00\"},{\"name\":\"Implied_Sequence\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Late_Items\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Parent_PP_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Path_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"PP_Status_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"PP_Type_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Predicted_Remaining_Duration\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Predicted_Remaining_Quantity\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Predicted_Total_Duration\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Process_Order\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"Prod_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"Production_Rate\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Source_PP_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"User_General_1\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"User_General_2\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"User_General_3\",\"type\":{\"type\":\"string\",\"logicalType\":\"marcher\",\"maxLength\":50},\"default\":\"\"},{\"name\":\"User_Id\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"op_code\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"time_key\",\"type\":{\"type\":\"string\",\"logicalType\":\"varchar\",\"maxLength\":100},\"default\":\"\"}]}"}

It looks like for all INT type, we have a default '0' or '00:00:00' there instead of NULL, so not sure what could be the reason for the above error and don't know how to fix.

Any help would be highly appreciated.

Thanks
Ramon

**Comment by ramonsgh** [comment]
Figured out what was wrong.

**Comment by BenCoughlan15** [comment]
Cn you tell us what was wrong?
