### ISSUE TITLE
RecordFieldTimestampExtractor.extract: The nested field named does not exist

### ISSUE THREAD

**Issue by yuryn** [confluentinc/kafka-connect-hdfs#316]
I am just trying new confluent release 4.1. When I change version from 4.0 to 4.1 Confluent HDFS Connector start reporting following error:
```
[2018-04-18 14:20:18,911] ERROR Exception on topic partition fulltext-searchweb-log-event-2:  (io.confluent.connect.hdfs.TopicPartitionWriter:403)
org.apache.kafka.connect.errors.DataException: The nested field named 'eventTime' does not exist.
	at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:53)
	at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:276)
	at io.confluent.connect.hdfs.TopicPartitionWriter.shouldRotateAndMaybeUpdateTimers(TopicPartitionWriter.java:512)
	at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:367)
	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
	at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:109)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Argument not a Struct or Map. Cannot get field 'eventTime' from: {referer=http://jirka-wheezy.fulltext-dev.tt-os1.dev:1234/?sId=Bv7Ei5Yg-qh136TFj2vY&sourceid=top&q=viden&oq=viden&aq=-1&su=e, headers={Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, Upgrade-Insecure-Requests=1, Connection=keep-alive, User-Agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0, Host=jirka-wheezy.fulltext-dev.tt-os1.dev:1234, Accept-Language=en-US,en;q=0.5, Accept-Encoding=gzip, deflate}, @topic=fulltext-searchweb-log-event, method=GET, removedCookies=[ftxt, ftxt_pref], localSessionId=Bv7EiN7jQoZW3YTvJfCa, @metadata={beat=filebeat, topic=fulltext-searchweb-log-event, type=doc, version=6.1.2}, eventType=request, uri=/?sId=Bv7EifXOQ9Cxo2grBdLx&sourceid=top&q=pardubice&oq=pardubice&aq=-1&su=e, cookies=__gfp_64b=uzaHw2yquXeHc5JvIVOwSw81BrTHDQJe5o5dn5fE3GL.h7; sid=14173330419605563879, parentId=Bv7EifXOQ9Cxo2grBdLx, duration=3.67022013664, hostname=jirka-wheezy.novalocal, @timestamp=2018-04-12T08:31:40.717Z, eventData={boostedHints=[zbozi/product], aclient={responses={lama=200}}, offset=0, hwType=desktop, hints=[{cached=false, hintType=zbozi/product}, {cached=false, hintType=mapy/muni2}, {cached=false, hintType=encyklopedie/encyklopedie}, {cached=false, hintType=firmy/search}], query=pardubice, userAgent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0, source=top, firstSrchAttemptId=0, rpref={uiLang=cs, searchLang=cs, resultType=all}, tracks=e, rqId=Ws8ZYH8AAQEAAHFBVyAAAAAA, result=[{titleOrigin=docTitle, premiseId=355731, urlHash=3861d957ee09c351, relevanceAdjust=-7, majorLang=CS, type=result/cr, url=https://www.pardubice.eu/, porn=false}, {titleOrigin=docTitle, premiseId=12861588, urlHash=ca42206027b61654, relevanceAdjust=-8, majorLang=CS, type=result/cr, url=http://www.ipardubice.cz/, porn=false}, {type=hint/mapy/muni2}, {titleOrigin=docTitle, urlHash=4e9a45f8210bf169, relevanceAdjust=-6, majorLang=CS, type=result/cr, url=http://www.pardubice.cz/, porn=false}, {titleOrigin=docTitle, relevanceAdjust=-7, urlHash=e96a60bf4de3ced0, majorLang=CS, anchors=[https://cs.wikipedia.org/wiki/Pardubice#Etymologie, https://cs.wikipedia.org/wiki/Pardubice#D%C4%9Bjiny, https://cs.wikipedia.org/wiki/Pardubice#Geografie, https://cs.wikipedia.org/wiki/Pardubice#Obyvatelstvo, https://cs.wikipedia.org/wiki/Pardubice#Spr%C3%A1vn%C3%AD_%C4%8Dlen%C4%9Bn%C3%AD_a_v%C3%BDvoj, https://cs.wikipedia.org/wiki/Pardubice#Sport], type=result/cr, url=https://cs.wikipedia.org/wiki/Pardubice, porn=false}, {titleOrigin=docTitle, premiseId=580010, urlHash=df252cbd7cab37f2, relevanceAdjust=-7, majorLang=CS, type=result/cr, url=http://www.hcdynamo.cz/, porn=false}, {type=hint/zbozi/product}, {titleOrigin=docTitle, premiseId=212725, urlHash=62b6369cea234c65, relevanceAdjust=-6, majorLang=CS, type=result/cr, url=http://www.dpmp.cz/, porn=false}, {titleOrigin=docTitle, premiseId=12940305, relevanceAdjust=-6, urlHash=674a71e42b87d034, majorLang=CS, type=result/cr, url=https://palacpardubice.cz/, porn=false}, {titleOrigin=docTitle, premiseId=364320, urlHash=5d4afe44be41a9c1, relevanceAdjust=-6, majorLang=CS, type=result/cr, url=https://www.upce.cz/, porn=false}, {type=hint/encyklopedie/encyklopedie}, {titleOrigin=docTitle, premiseId=161468, relevanceAdjust=-6, urlHash=e0c5adbfe678514d, majorLang=CS, type=result/cr, url=https://www.airport-pardubice.cz/, porn=false}, {titleOrigin=docTitle, urlHash=7b8c44cea5b7853f, relevanceAdjust=-5, majorLang=CS, type=result/cr, url=https://www.turistika.cz/vylety/pardubice/detail, porn=false}, {type=relatedSearches/bottom}], lolaInfo={longtailQuery=false, used=false, statusMessage=OK, status=200}, metasearchInfo={serpQuality=0, pornFilterLevel=noporn, docsFound=28450992, query={actualTopic=false, languages=[{langCode=cs, langProbability=0.937674150504}], query=pardubice, commerciality=0.0928630977869, groups=[{length=1, groupEntity={nuts={prob=1, nuts=[CZ0532555134], id=1258, type=municipality}, name=Pardubice, entity=PLACE_CITY}, weight=1, id=0, type=ENTITY}, {groupEntity={name=, entity=Wikidata_Human_geo}, length=1, weight=1, id=1, type=ENTITY}, {length=1, groupEntity={name=, entity=Strong_Modifiers}, weight=1, id=2, type=ENTITY}, {length=1, weight=1, id=3, type=QUERYSITE}], naviness=-0.0962533652782, tokens=[{original={tokenizerFlags=1, orig=pardubice, tokenGroups=[0, 1, 2, 3], paddingRight=, lemma=pardubice, tag=k1gInSc1wM, isUrlOrEmail=false, lang=cs:0.926718, , paddingLeft=, order=0, token=pardubice}, derived=[]}]}, foreigness=0.138163805008, randomizationUsed=false, spam={relevanceDiff=12.9164123535, spamWeight=94.4259338379}, statusMessage=OK, status=200}, servers=[{code=208, serverName=metasearchPrepare, state=ok}, {code=200, serverName=metasearchSearch, state=ok}, {code=204, serverName=queryCorrector, state=ok}, {serverName=sklik, state=ok, timeout=0.0785400867462}, {serverName=relatedSearches, state=ok, timeout=0.0372591018677}, {code=204, serverName=sauto, state=ok, timeout=0.312216997147}, {code=200, serverName=zbozi, state=ok, timeout=0.270425081253}, {code=204, serverName=videa, state=ok, timeout=0.0458240509033}, {code=200, serverName=mapy, state=ok, timeout=0.618330001831}, {code=204, serverName=sreality, state=ok, timeout=0.29914689064}, {code=404, serverName=miniappslexical, state=ok, timeout=0.0384430885315}, {code=204, serverName=obrazky, state=ok, timeout=0.0379140377045}, {code=200, serverName=encyklopedie, state=ok, timeout=0.212800979614}, {code=204, serverName=kupi, state=ok, timeout=0.0357549190521}, {errorMessage=Server returned non 200 answer: 404 Not Found, serverName=fakehint, state=error, timeout=0.0230329036713}, {code=204, serverName=hintapi, state=ok, timeout=0.170590877533}, {errorMessage=Server returned non 200 answer: 404 Not Found, serverName=tvhint, state=error, timeout=0.0190379619598}, {code=200, serverName=demagog, state=ok, timeout=0.00890398025513}, {code=200, serverName=krastysport, state=ok, timeout=0.00367188453674}, {serverName=volnycas, state=error, timeout=2.50152397156}, {code=404, serverName=sdovolena, state=ok, timeout=0.0353059768677}, {errorMessage=Key "hintType" does not exist., serverName=sdovolena, state=error}, {code=200, serverName=zoo, state=ok, timeout=0.00367188453674}, {code=200, serverName=recenze, state=ok, timeout=0.00332808494568}, {code=500, serverName=sbazar, state=ok, timeout=0.00236296653748}, {code=200, serverName=firmy, state=ok, timeout=1.09972500801}, {code=204, serverName=miniapps, state=ok, timeout=0.00236296653748}], firstPage=true, relatedSearch=[[idos, idnes, mhd pardubice, globus pardubice], [cinestar pardubice, pardubické panství, sport v pardubicích, města v okrese pardubice]], sklikRight=[], gsid=14173330419605563879, pref={id=_RuqXytljsWNviic}, limit=10, isHttps=false, relatedSearchesQuery=pardubice}, meta={schema=searchweb, node=fooo, pod=barr, version=1-2-0}, service=fulltext, requestId=Bv7EijA9beCpo2zDUmA5, clientIp=10.0.51.74, eventTime=2018-04-12T08:31:29.505168Z, eventName=fulltext:cs, startTime=1.52352188951E9, api=103}
	at io.confluent.connect.storage.util.DataUtils.getField(DataUtils.java:37)
	at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:49)
	... 16 more
```
It reads json records from kafka topics and writes them to hdfs. Here is my connectors configuration:
```
[
    {
        "name": "hdfs-sink",
        "config": {
            "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
            "partition.duration.ms": "3600000",
            "flush.size": "100000000",
            "tasks.max": "4",
            "topics": "fulltext-searchweb-log-event",
            "timezone": "UTC",
            "hadoop.conf.dir": "/etc/connect-configs/",
            "hdfs.url": "hdfs://cdh5/tmp",
            "logs.dir": "/logs",
            "topics.dir": "/topics",
            "rotate.interval.ms": "900000",
            "locale": "en",
            "format.class": "io.confluent.connect.hdfs.json.JsonFormat",
            "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
            "name": "hdfs-sink",
            "path.format": "YYYY/MM/dd/HH",
            "timestamp.extractor": "RecordField",
            "timestamp.field": "eventTime"
        }
    },
    {
        "name": "hdfs-sink-5m",
        "config": {
            "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
            "partition.duration.ms": "300000",
            "flush.size": "100000000",
            "tasks.max": "4",
            "topics": "fulltext-searchweb-log-event",
            "timezone": "UTC",
            "hadoop.conf.dir": "/etc/connect-configs/",
            "hdfs.url": "hdfs://cdh5/tmp",
            "logs.dir": "/logs-5m",
            "topics.dir": "/topics",
            "rotate.interval.ms": "300000",
            "locale": "en",
            "format.class": "io.confluent.connect.hdfs.json.JsonFormat",
            "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
            "name": "hdfs-sink-5m",
            "path.format": "'5m'/YYYY/MM/dd/HH/mm",
            "timestamp.extractor": "RecordField",
            "timestamp.field": "eventTime"
        }
    }
]
```

Thanks for any suggestions what is wrong?

**Comment by yuryn** [comment]
probably problem is caused by missing return here:
```
diff --git a/core/src/main/java/io/confluent/connect/storage/util/DataUtils.java b/core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
index 9002f2f..3a7311d 100644
--- a/core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
+++ b/core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
@@ -33,6 +33,7 @@ public class DataUtils {
       if (field == null) {
         throw new DataException(String.format("Unable to find nested field '%s'", fieldName));
       }
+      return field;
     }
     throw new DataException(String.format(
           "Argument not a Struct or Map. Cannot get field '%s' from: %s",

```

**Comment by cricket007** [comment]
@yuryn Have you been able to upgrade? Is this still relevant?

**Comment by yuryn** [comment]
no problem with this anymore, merge request fixed the problem.

**Comment by cricket007** [comment]
@yuryn  Feel free to close the issue
