### ISSUE TITLE
java.lang.NoClassDefFoundError: io/confluent/common/config/AbstractConfig

### ISSUE THREAD

**Issue by rupeshn** [confluentinc/kafka-connect-hdfs#318]
While using the project using master branch I get error java.lang.NoClassDefFoundError: io/confluent/common/config/AbstractConfig
[2018-04-21 10:47:02,044] INFO StandaloneConfig values: 
	access.control.allow.methods = 
	access.control.allow.origin = 
	bootstrap.servers = [localhost:9092]
	internal.key.converter = class org.apache.kafka.connect.json.JsonConverter
	internal.value.converter = class org.apache.kafka.connect.json.JsonConverter
	key.converter = class io.confluent.connect.avro.AvroConverter
	offset.flush.interval.ms = 60000
	offset.flush.timeout.ms = 5000
	offset.storage.file.filename = /tmp/connect.offsets
	plugin.path = [/usr/local/share/kafka/plugins]
	rest.advertised.host.name = null
	rest.advertised.port = null
	rest.host.name = null
	rest.port = 8083
	task.shutdown.graceful.timeout.ms = 5000
	value.converter = class io.confluent.connect.avro.AvroConverter
 (org.apache.kafka.connect.runtime.standalone.StandaloneConfig:223)
[2018-04-21 10:47:02,526] INFO Logging initialized @46007ms (org.eclipse.jetty.util.log:186)
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/common/config/AbstractConfig
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:54)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:54)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.confluent.connect.avro.AvroConverter.configure(AvroConverter.java:59)
	at org.apache.kafka.connect.runtime.Worker.<init>(Worker.java:99)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:76)
Caused by: java.lang.ClassNotFoundException: io.confluent.common.config.AbstractConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

**Comment by cricket007** [comment]
Can you please add an output similar to the following?

Tested on 4.0.1 tarball release

### List confluent common classpath

```sh
# ls -l /usr/share/java/confluent-common/
total 2940
-rw-r--r-- 1 1000 1000    5029 Mar 29 21:33 build-tools-4.0.1.jar
-rw-r--r-- 1 1000 1000   23533 Mar 29 21:33 common-config-4.0.1.jar
-rw-r--r-- 1 1000 1000   41564 Mar 29 21:33 common-metrics-4.0.1.jar
-rw-r--r-- 1 1000 1000   20808 Mar 29 21:33 common-utils-4.0.1.jar
-rw-r--r-- 1 1000 1000   87325 Mar 29 21:33 jline-0.9.94.jar
-rw-r--r-- 1 1000 1000  489884 Mar 29 21:33 log4j-1.2.17.jar
-rw-r--r-- 1 1000 1000 1330394 Mar 29 21:33 netty-3.10.5.Final.jar
-rw-r--r-- 1 1000 1000   41203 Mar 29 21:33 slf4j-api-1.7.25.jar
-rw-r--r-- 1 1000 1000   74798 Mar 29 21:33 zkclient-0.10.jar
-rw-r--r-- 1 1000 1000  871369 Mar 29 21:33 zookeeper-3.4.10.jar
```

### Finding class in Common Config JAR

```
# jar -tvf /usr/share/java/confluent-common/common-config-*.jar | grep Abstract
  9539 Thu Mar 29 21:33:58 UTC 2018 io/confluent/common/config/AbstractConfig.class
```

**Comment by pmid** [comment]
I faced the same problem, using the tar.gz, version 4.1 .

I could solve it by copying <common-config-4.1.0.jar> to a folder added to the CLASSPATH for connect-standalone (where I already put external jars, such as jdbc drivers).

I had to add also <common-utils-4.1.0.jar>, as io.confluent.common.utils.Utils was non found as well.

Hope this can help.


Regards,

Paolo

**Comment by cricket007** [comment]
Thanks @pmid - I assume you built those from source?

Also, copying those files into `kafka-connect-storage-common` would be the correct location. Any directory starting with `kafka-connect` is added to the CLASSPATH

**Comment by pmid** [comment]
@cricket007  no, I did't build from the sources I downloaded the tar.gz from https://www.confluent.io/download/ and extracted it to a folder.

**Comment by pmid** [comment]
@cricket007  sorry, I need to add some context, as I'm working in an "abnormal" environment.
I'm working on a Cloudera (CDH 5.13.1) cluster, running kafka 0.11 .

I'm experimenting with kafka connect, and my current needs are:
- ingest some data from oracle tables
- process/transform them (using kafka streams)
- save processed data to kudu
- save raw data to hdfs

So I also downloaded Confluent package, and extracted everything to a folder.
Maybe it's not very wise to use latest Confluent connectors with kafka (connect) 0.11, but I'm just testing it, as I wrote.

So I'm using kafka connect (standalone) version 0.11 against the 4.1 connectors.

It's true that the jars are present in the Confuent folder, but for some reason they are not loaded correctly by the HdfsSinkConnector.
I verified that the classes are present inside the jars, and then tried to work around the problem by adding the jars to the folder in the classpath.
There are no other/older versions of the jars on the machine.

No such problems instead with the JdbcSourceConnector and KuduSinkConnector .

**Comment by cricket007** [comment]
Okay, makes more sense 

> Maybe it's not very wise to use latest Confluent connectors with kafka (connect) 0.11

In theory, the Connect Workers can be upgraded before the brokers

>  I'm using kafka connect (standalone) version 0.11 against the 4.1 connectors

If you're running `connect-standalone` from within the confluent-4.1.0 package extraction like so rather than a `connect-standalone` script installed by CDH , then the CLASSPATH should be correct 

```
cd /path/to/confluent-4.1.0/bin
./connect-standalone ....
```

Otherwise, yes, you would need to copy the HDFS Connect package and confluent-common packages into the Cloudera's Kafka Classpath

**Comment by pmid** [comment]
I am running the CDH connect-standalone, I will try the other way too  - thanks a lot.

**Comment by cricket007** [comment]
Yup. Also, you don't need to run Kafka Connect from the CDH cluster itself.

For example, if you plan on having continuous data flow from Kafka, it might be useful to have dedicated servers for running a "Kafka Connect cluster"

**Comment by pmid** [comment]
Thanks for the hint - at the moment the amount of data is very limited, moving Kafka Connect outside CDH was already on the TODO list for the future :-)

**Comment by pmid** [comment]
> If you're running connect-standalone from within the confluent-4.1.0 package extraction like so rather than a connect-standalone script installed by CDH , then the CLASSPATH should be correct
> cd /path/to/confluent-4.1.0/bin
> ./connect-standalone ....

Hi, I confirm that launching it this way it starts with no problem - thanks.

**Comment by kkonstantine** [comment]
Confluent platform (OSS and Enterprise) ships with `bin/connect-distributed` and `bin/connect-standalone` scripts that a few dependencies such as `confluent-common` to the `CLASSPATH` correctly. For Connectors, after version AK 0.11 the recommended way is to use the `plugin.path` to achieve classloading isolation between connectors and their dependencies. 

I understand you didn't use the above executable scripts, therefore, the `AbstractConfig` class was not in your classpath. You'd have to add it manually yourself. 

The issue would be same for standalone or distributed modes. 

Closing here.
