### ISSUE TITLE
connector not accepting HourlyPartitioner

### ISSUE THREAD

**Issue by thereallogani** [confluentinc/kafka-connect-hdfs#332]
I'm trying to set the connector to use the HourlyPartitioner rather than the default, but the worker fails on start up with the message: 

`
[2018-06-05 19:51:55,895] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:228)
org.apache.kafka.common.config.ConfigException: Invalid value io.confluent.connect.hdfs.partitioner.HourlyPartitioner for configuration partitioner.class: Class io.confluent.connect.hdfs.partitioner.HourlyPartitioner could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:724)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
        at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:368)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:272)
        at org.apache.kafka.connect.util.KafkaBasedLog.createProducer(KafkaBasedLog.java:242)
        at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:127)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:109)
        at org.apache.kafka.connect.runtime.Worker.start(Worker.java:174)
        at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:109)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:215)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

It also fails when I explicitly set the partitioner to the DefaultPartitioner.
The relevant configs I'm using are:

`
plugin.path=/usr/share/java/,/usr/share/java/kafka-connect-hdfs,/usr/share/java/kafka-connect-hdfs/storage-common,/usr/share/java/confluent-common
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
partitioner.class=io.confluent.connect.hdfs.partitioner.HourlyPartitioner
`

With respect to the plugin path, I tried being explicit with the plugins after it failed to recognize this, but that didn't seem to work either.

It's worth noting that the default partitioner is working fine when I don't specify any changes, and I'm using confluent version 4.1.1.

Any help diagnosing this would be much appreciated.

**Comment by rhauch** [comment]
The `plugin.path` is wrong: do not include any specific plugin directories (e.g., `/usr/share/java/confluent-common `, or `/usr/share/java/kafka-connect-hdfs/storage-common` or `/usr/share/java/kafka-connect-hdfs`), but only include the _parent_ directories that contain plugin directories (e.g., `/usr/share/java/`)

Also, make sure that `plugin.path` goes in your Connect _worker_ configuration, and then restart the worker. It should not be in the same file as the `connector.class` or `partitioner.class` file.

**Comment by thereallogani** [comment]
Ah, OK. I didn't realize that the connector.class/partitioner.class weren't supposed to be in the worker configuration and that seems to have broken it.

Everything works now, thanks a lot for the help!
