### ISSUE TITLE
NullPointerException when using Avro converter

### ISSUE THREAD

**Issue by Arttii** [confluentinc/kafka-connect-hdfs#36]
Hi,

We are getting this error 

`java.lang.NullPointerException
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:863)
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:946)
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:751)
    at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:103)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:266)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Exception in thread "WorkerSinkTask-elasticsearch-sink-0" java.lang.NullPointerException
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:863)
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:946)
    at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:751)
    at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:103)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:266)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)`

 
if we use the Schema Registry with this schema and value
    `{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}]}`

`"expiration_date":null `

   

in a row coming from the JDBC connector.

**Comment by Ishiihara** [comment]
Closing this as it is fixed by https://github.com/confluentinc/schema-registry/pull/254
