### ISSUE TITLE
Hive integration is not currently supported with JSON format

### ISSUE THREAD

**Issue by chengang2** [confluentinc/kafka-connect-hdfs#373]
format.class=io.confluent.connect.hdfs.json.JsonFormat
java.lang.UnsupportedOperationException: Hive integration is not currently supported with JSON format
        at io.confluent.connect.hdfs.json.JsonFormat.getHiveFactory(JsonFormat.java:68)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:292)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
        at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:82)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:190)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by cricket007** [comment]
Are you sure you need to post the stacktrace? It's a known issue. 

In order to create a Hive table from JSON, you must know the schema ahead of time.

In order to know the schema, it must exist in the message. https://www.google.com/amp/rmoff.net/2017/09/06/kafka-connect-jsondeserializer-with-schemas-enable-requires-schema-and-payload-fields/amp/

If a schema exists in the message, I believe you can actually use AvroFormat

**Comment by cricket007** [comment]
I understand that.

If you look at the code, JSON doesn't support Hive. https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/json/JsonFormat.java

If you look at the Avro or Parquet folders, there is Hive support. 

Your Kafka topics don't need to contain Avro data in order to write to Avro data to HDFS. Similarly, you wouldn't be able to put Parquet data into a topic.

If you set `value.converter` to be JSON, set the schemas property to be enabled, then you can use either Avro or Parquet formats, and then you'll be able to get a Hive table
