### ISSUE TITLE
Not possible to connect to HDFS if I don't set something like that "hdfs://hostname:port"

### ISSUE THREAD

**Issue by NastasiaSaby** [confluentinc/kafka-connect-hdfs#387]
Version Kafka : 1.0.0

I'm not able to connect to HDFS if I set somethink like that:
```
hdfs.url": "/user/myuser/mydirectory" 
```

or like that (note that there's no port):

```
hdfs.url": "hdfs://hostname/user/myuser/mydirectory" 
```
I have this error : 

```
state: "FAILED",
trace: "java.lang.NullPointerException at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:135) at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:377) at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:576) at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:177) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```
Is it normal?
Did I miss something in the documentation?
Could you help me please?
I find no anwser and no solution to call my namenodes indifferently.

Thank you for your answer

**Comment by cricket007** [comment]
Sounds like your `hadoop.conf.dir` is missing or not configured to a directory that contains the correct descriptions of `core-site.xml`

**Comment by NastasiaSaby** [comment]
Exactly. I haven't understood that I need to add "hadoop.conf.dir" in my configuration.
Thank you for your help.
I close this issue.

**Comment by NastasiaSaby** [comment]
Exactly, I haven't understood that I need to add "hadoop.conf.dir" when HA HDFS.
