### ISSUE TITLE
Misleading connection exception when restarting workers connected to HA HDFS

### ISSUE THREAD

**Issue by jeqo** [confluentinc/kafka-connect-hdfs#391]
I'm running HDFS Connector, against an HA-enabled Hadoop cluster. When restarting or redeploying connectors, I'm getting a `INFO Retrying connect to server: ... Already tried 16 time(s); maxRetries=45 (org.apache.hadoop.ipc.Client:837)`. 

The only way to fix this is by deleting manually `/logs` directory and restart workers. 

This makes really annoying to deploy new connectors and manage a connect cluster, as any worker restart will restart connectors and trigger this issue again.

**Comment by saidbouras** [comment]
I have the same issue with an HA hadoop cluster.

The problem is that the emitters wants to confirm that the connector works by sending few messages (2 or 3) but it is never read due this error.
I noticed that the error logs continue to show up even when I delete the connector, so it means that the thread that handle the hdfs client is still here and has lot connection to the hadoop cluster.

By the way, it says in the doc, that `hdfs.url` is deprecated, better use `store.url` but with either confluent 4.1 or 5.0, the connector failed due to an NPE on `hdfs.url`.

**Comment by jeqo** [comment]
Stacktrace: 

```
01-15 14:00:15,982] ERROR Error applying WAL file: hdfs://HA:8020//logs/TOPIC_NAME/1/log, {} (io.confluent.connect.hdfs.wal.FSWAL:131)
java.io.IOException: Cannot obtain block length for LocatedBlock{BP-1623737282-XXX.XXX.XXX.XXX-1511948221547:blk_1095732807_22021567; getBlockSize()=526; corrupt=false; offset=0; locs=[DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-698cdd28-324a-40f3-aadd-5664b90a03b0,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-689145d9-3b34-40e4-96c7-8f70e5fac37e,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-6d4cbdce-b303-4d90-8ef1-0bb7b826ad64,DISK]]}
	at org.apache.hadoop.hdfs.DFSInputStream.readBlockLength(DFSInputStream.java:428)
	at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:336)
	at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
	at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
	at io.confluent.connect.hdfs.wal.WALFile$Reader.openFile(WALFile.java:568)
	at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:453)
	at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:107)
	at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:626)
	at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
	at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:380)
	at io.confluent.connect.hdfs.DataWriter.open(DataWriter.java:444)
	at io.confluent.connect.hdfs.HdfsSinkTask.open(HdfsSinkTask.java:133)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:612)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:672)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:283)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:422)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:343)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1181)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:444)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:317)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


[2019-01-15 14:00:16,033] ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED (io.confluent.connect.hdfs.TopicPartitionWriter:277)
org.apache.kafka.connect.errors.DataException: java.io.IOException: Cannot obtain block length for LocatedBlock{BP-1623737282-XXX.XXX.XXX.XXX-1511948221547:blk_1095732807_22021567; getBlockSize()=526; corrupt=false; offset=0; locs=[DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-698cdd28-324a-40f3-aadd-5664b90a03b0,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-689145d9-3b34-40e4-96c7-8f70e5fac37e,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-6d4cbdce-b303-4d90-8ef1-0bb7b826ad64,DISK]]}
	at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:133)
	at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:626)
	at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
	at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:380)
	at io.confluent.connect.hdfs.DataWriter.open(DataWriter.java:444)
	at io.confluent.connect.hdfs.HdfsSinkTask.open(HdfsSinkTask.java:133)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:612)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:672)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:283)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:422)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:343)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1181)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:444)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:317)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot obtain block length for LocatedBlock{BP-1623737282-XXX.XXX.XXX.XXX-1511948221547:blk_1095732807_22021567; getBlockSize()=526; corrupt=false; offset=0; locs=[DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-698cdd28-324a-40f3-aadd-5664b90a03b0,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-689145d9-3b34-40e4-96c7-8f70e5fac37e,DISK], DatanodeInfoWithStorage[XXX.XXX.XXX.XXX:1019,DS-6d4cbdce-b303-4d90-8ef1-0bb7b826ad64,DISK]]}
	at org.apache.hadoop.hdfs.DFSInputStream.readBlockLength(DFSInputStream.java:428)
	at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:336)
	at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
	at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
	at io.confluent.connect.hdfs.wal.WALFile$Reader.openFile(WALFile.java:568)
	at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:453)
	at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:107)
	... 27 more
```

**Comment by jeqo** [comment]
I haven't managed to find the cause for this issue so far. I follow these steps to estabilize the connector tasks:

- Move to standalone mode to avoid run-time scheduling that cause tasks to be restarted and throw exception explained above.
- Configure a random logs directory everytime workers are restarted, as restarting with the same directory, even with standalone mode, cause the exception to happen.
- Manual distribution of connectors between two connector workers. Scheduling all tasks (around 30) in one worker was causing that after 20/30 minutes of a worker running to start throwing the same exception. I haven't found the limit that triggers this behavior yet. But spreading tasks on two workers with the previous configurations has estabilized my deployment.

I'll close this issue until I find a way to recreate this behavior to be able to debug it properly.
