### ISSUE TITLE
Cannot get out of Exception when closing the temporary file

### ISSUE THREAD

**Issue by User1773** [confluentinc/kafka-connect-hdfs#407]
Hello,

For some reason, when writing the parquet temporary file into HDFS filesystem,we got this exception:
2019/01/18 14:40:05 ERROR 2525665 [pool-3-thread-28] connect.hdfs.TopicPartitionWriter.write(403): Exception on topic partition SYS_4G_PCMD_IMSI_PROC-7:
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: can not write PageHeader(type:DICTIONARY_PAGE, uncompressed_page_size:480, compressed_page_size:364, dictionary_page_header:DictionaryPageHeader(num_values:60, encoding:PLAIN_DICTIONARY))
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:99) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:655) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:662) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:386) [kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374) [kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:109) [kafka-connect-hdfs-4.0.1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:508) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:211) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:179) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214) [connect-runtime-1.0.2-cp1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.IOException: can not write PageHeader(type:DICTIONARY_PAGE, uncompressed_page_size:480, compressed_page_size:364, dictionary_page_header:DictionaryPageHeader(num_values:60, encoding:PLAIN_DICTIONARY))
        at org.apache.parquet.format.Util.write(Util.java:224) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.Util.writePageHeader(Util.java:61) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDictionaryPageHeader(ParquetMetadataConverter.java:1010) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetFileWriter.writeDictionaryPage(ParquetFileWriter.java:332) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writeToFileWriter(ColumnChunkPageWriteStore.java:188) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore.flushToFileWriter(ColumnChunkPageWriteStore.java:251) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:170) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:301) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97) ~[kafka-connect-hdfs-4.0.1.jar:?]
        ... 16 more
Caused by: shaded.parquet.org.apache.thrift.transport.TTransportException: java.nio.channels.ClosedChannelException
        at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.transport.TTransport.write(TTransport.java:105) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:424) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:431) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBeginInternal(TCompactProtocol.java:194) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBegin(TCompactProtocol.java:176) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.InterningProtocol.writeFieldBegin(InterningProtocol.java:74) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.PageHeader.write(PageHeader.java:918) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.Util.write(Util.java:222) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.Util.writePageHeader(Util.java:61) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDictionaryPageHeader(ParquetMetadataConverter.java:1010) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetFileWriter.writeDictionaryPage(ParquetFileWriter.java:332) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writeToFileWriter(ColumnChunkPageWriteStore.java:188) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore.flushToFileWriter(ColumnChunkPageWriteStore.java:251) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:170) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:301) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97) ~[kafka-connect-hdfs-4.0.1.jar:?]
        ... 16 more
Caused by: java.nio.channels.ClosedChannelException
        at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1546) ~[hadoop-hdfs-2.7.3.jar:?]
        at org.apache.hadoop.fs.FSOutputSummer.write(FSOutputSummer.java:104) ~[hadoop-common-2.7.3.jar:?]
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:58) ~[hadoop-common-2.7.3.jar:?]
        at java.io.DataOutputStream.write(DataOutputStream.java:107) ~[?:1.8.0_181]
        at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.transport.TTransport.write(TTransport.java:105) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:424) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:431) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBeginInternal(TCompactProtocol.java:194) ~[parquet-format-2.3.1.jar:2.3.1]
        at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBegin(TCompactProtocol.java:176) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.InterningProtocol.writeFieldBegin(InterningProtocol.java:74) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.PageHeader.write(PageHeader.java:918) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.Util.write(Util.java:222) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.Util.writePageHeader(Util.java:61) ~[parquet-format-2.3.1.jar:2.3.1]
        at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDictionaryPageHeader(ParquetMetadataConverter.java:1010) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetFileWriter.writeDictionaryPage(ParquetFileWriter.java:332) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writeToFileWriter(ColumnChunkPageWriteStore.java:188) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore.flushToFileWriter(ColumnChunkPageWriteStore.java:251) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:170) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:301) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97) ~[kafka-connect-hdfs-4.0.1.jar:?]
        ... 16 more
...

It is likely that the socket was closed in HDFS side. 
But then kafka-connect-hdfs is infinitly looping on the temporary file close and raising this exception:
2019/01/18 14:40:10 ERROR 2530667 [pool-3-thread-28] connect.hdfs.TopicPartitionWriter.write(403): Exception on topic partition SYS_4G_PCMD_IMSI_PROC-7:
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:99) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:655) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:662) ~[kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:386) [kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374) [kafka-connect-hdfs-4.0.1.jar:?]
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:109) [kafka-connect-hdfs-4.0.1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:508) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:211) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:179) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170) [connect-runtime-1.0.2-cp1.jar:?]
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214) [connect-runtime-1.0.2-cp1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.error(ParquetFileWriter.java:185) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.startBlock(ParquetFileWriter.java:177) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetFileWriter.startBlock(ParquetFileWriter.java:287) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:168) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:301) ~[parquet-hadoop-1.9.0.jar:1.9.0]
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97) ~[kafka-connect-hdfs-4.0.1.jar:?]
        ... 16 more

It looks like the kafka-connect-hdfs is not managing correctly the problem with socker close.

**Comment by User1773** [comment]
After some investigation, This issue is like https://github.com/confluentinc/kafka-connect-hdfs/issues/143 or at least beahavior where connect is stuck into SHOULD_ROTATE state.

**Comment by dcsobral** [comment]
I got the same stuff with avro files. My own exception, caused by the cluster being shutdown and then brought up again, was this:
```
org.apache.kafka.connect.errors.DataException: java.io.IOException: Got error, status message , ack with firstBadLink as 10.3.5.30:50010
        at io.confluent.connect.hdfs.avro.AvroRecordWriterProvider$1.close(AvroRecordWriterProvider.java:97)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:656)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:663)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:389)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:106)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:537)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:315)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:218)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:186)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Got error, status message , ack with firstBadLink as 10.3.5.30:50010
        at org.apache.hadoop.hdfs.protocol.datatransfer.DataTransferProtoUtil.checkBlockOpStatus(DataTransferProtoUtil.java:142)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1359)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
```
What is most galling is that there's a simple solution right there: on `TopicPartitionWriter`, if an exception is caught in the state machine, discard all data for the topic-partition, and change state to `RECOVERY_STARTED`. It would be preferable to have a retry count, and only discard work if the retry threshold is reached without progress.

**Comment by kaushiksrinivas** [comment]
#439

**Comment by EasonLee007** [comment]
Hi User1773, is your problem solved? i meet same issue now, i have check the HDFS is health and disk is not full,so if any idea about this issue? thanks
