### ISSUE TITLE
IOException when sending JSON to S3 with custom partitioner

### ISSUE THREAD

**Issue by vyrwu** [confluentinc/kafka-connect-hdfs#413]
I am getting IOExceptions when loading HDFS Connector with [custom partitioner](https://github.com/vyrwu/monaka/tree/field-time-partitioner) to Kafka Connect. 

```
connect            | [2019-02-14 16:51:16,929] INFO Getting path status for s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (test/logs/json-data/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:16,976] INFO Getting path status for s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (test/logs/json-data/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,017] INFO List status for path: s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,017] INFO Getting path status for s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (test/logs/json-data/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,060] INFO Getting path status for s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (test/logs/json-data/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,102] INFO Opening 's3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log' for reading (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,102] INFO Getting path status for s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log (test/logs/json-data/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,145] INFO Actually opening file test/logs/json-data/0/log at pos 0 (org.apache.hadoop.fs.s3a.S3AFileSystem)
connect            | [2019-02-14 16:51:17,195] ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED (io.confluent.connect.hdfs.TopicPartitionWriter)
connect            | org.apache.kafka.connect.errors.DataException: Error creating writer for log file s3a://<my AWS key>:<my AWS secret>@bucket/test/logs/json-data/0/log
connect            | 	at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
connect            | 	at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
connect            | 	at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:626)
connect            | 	at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
connect            | 	at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:321)
connect            | 	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
connect            | 	at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
connect            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            | 	at java.lang.Thread.run(Thread.java:748)
connect            | Caused by: java.io.IOException: Not supported
connect            | 	at org.apache.hadoop.fs.s3a.S3AFileSystem.append(S3AFileSystem.java:268)
connect            | 	at org.apache.hadoop.fs.FileSystem.append(FileSystem.java:1176)
connect            | 	at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:171)
connect            | 	at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:77)
connect            | 	at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)
connect            | 	... 17 more

```

I set up Kafka Connect HDFS to write data to S3. [This is how I did it.](https://gist.github.com/jcustenborder/63d22be110109a8443621fb99c06de36)
I need this setup as Kafka-to-S3 does not provide parquet format support. Please not that I am using JSON here for this example. My connector config: 
```
{
    "name": "hdfs-sink-connector",
    "config": {
        "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
        "tasks.max": "1",
        "topics": "json-data",
        "hdfs.url": "s3a://<my AWS key>:<my AWS secret>@bucket/test",
        "format.class": "io.confluent.connect.hdfs.json.JsonFormat",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "flush.size": "1",
        "rotate.interval.ms": "1000",
        "partitioner.class": "com.jametson.monaka.partitioner.FieldAndMonthlyPartition",
        "partition.field.name": "channel",
        "partition.time.field.name": "time",
        "partition.include.field.name": "false"
    }
}
```

Sorry if this is more relevant for AWS forum. Any bells?

**Comment by cricket007** [comment]
The custom partitioner is not the problem... 

As mentioned in the gist, using s3a filesystem won't work with the write-ahead-log (WAL). 

The source code of hadoop-aws supports that statement - https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L1052-L1063

> Kafka-to-S3 does not provide parquet format support
1. You seem to be using JsonFormat, though
2. The existing S3 Connector might not, but there are still other options like NiFi or `pinterest/secor` that can write Parquet from Kafka

**Comment by vyrwu** [comment]
The problem was caused by write-ahead-log, which S3 does not support (you can't append to files in the bucket). But, this solution does work and you can actually write to S3 like this - you just need to remove the log file manually after restarting the Connector. If you don't, you will get this error.

NOTE: we only observed this behavior when using Docker. The log file was not created when we moved to local installation.
