### ISSUE TITLE
Kafka hdfs connect exception when datanode is restarted

### ISSUE THREAD

**Issue by swathimocharla** [confluentinc/kafka-connect-hdfs#415]
Hi,
I have a single HDFS writer that has 1 task. This is writing to HDFS with a single datanode. When the datanode goes for a restart, we see the following error is the 

```
{"type":"log", "host":"kconn1-ckaf-connect-786db9bd69-qwv9b", "level":"ERROR", "neid":"kafka-connect-8d51df5bc3b14006a3f9ddd87882e334", "system":"kafka-connect", "time":"2019-02-06T11:43:53.004Z", "timezone":"UTC", "log":"pool-5-thread-5 - io.confluent.connect.hdfs.TopicPartitionWriter - Exception on topic partition test_hdfs-0: "}
org.apache.kafka.connect.errors.DataException: Error creating writer for log file hdfs://10.75.172.215:8020/user/cloud-user/connect//logs/test_hdfs/0/log
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
        at io.confluent.connect.hdfs.wal.FSWAL.append(FSWAL.java:56)
        at io.confluent.connect.hdfs.TopicPartitionWriter.beginAppend(TopicPartitionWriter.java:701)
        at io.confluent.connect.hdfs.TopicPartitionWriter.appendToWAL(TopicPartitionWriter.java:692)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:421)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot obtain block length for LocatedBlock{BP-1881373902-10.75.172.215-1549272875195:blk_1073745690_4866; getBlockSize()=35; corrupt=false; offset=0; locs=[DatanodeInfoWithStorage[10.75.172.215:50010,DS-2479aa89-e1ac-4ad8-866a-b739d45c7710,DISK]]}
        at org.apache.hadoop.hdfs.DFSInputStream.readBlockLength(DFSInputStream.java:428)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:336)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
        at io.confluent.connect.hdfs.wal.WALFile$Reader.openFile(WALFile.java:551)
        at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:436)
        at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:158)
        at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:75)
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)
        ... 17 more
{"type":"log", "host":"kconn1-ckaf-connect-786db9bd69-qwv9b", "level":"INFO", "neid":"kafka-connect-8d51df5bc3b14006a3f9ddd87882e334", "system":"kafka-connect", "time":"2019-02-06T11:44:01.911Z", "timezone":"UTC", "log":"pool-5-thread-5 - io.confluent.connect.hdfs.TopicPartitionWriter - Starting commit and rotation for topic partition test_hdfs-0 with start offsets {partition=0=15} and end offsets {partition=0=19}"}

```
the HDFS Writer seems to be having issues with "block pipeline recovery". When the datanode that is hosting one of the replicas currently being written to is restarted, then HDFS has to initiate block pipeline recovery. The client must be able to deal with this, but is not the case.

To overcome this, we tried the following:
1. recover the lease on the log file from hdfs.
`hdfs debug recoverLease -path /user/cloud-user/connect/logs/test_hdfs/0/log -retries 2`
After this, writing to hdfs via the hdfs connect causes the following:
```
{"type":"log", "host":"kconn2-ckaf-connect-5d447bc64b-5z5wt", "level":"ERROR", "neid":"kafka-connect-8d51df5bc3b14006a3f9ddd87882e334", "system":"kafka-connect", "time":"2019-02-07T13:02:03.353Z", "timezone":"UTC", "log":"pool-5-thread-3 - io.confluent.connect.hdfs.wal.WALFile - Failed creating a WAL Writer: failed to create file /user/cloud-user/connect/logs/test_hdfs3/0/log for DFSClient_NONMAPREDUCE_-1151592587_47 for client 10.75.172.203 because current leaseholder is trying to recreate file.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:3294)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:3124)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3409)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:3373)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:629)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.append(AuthorizationProviderProxyClientProtocol.java:131)

```
2. Instead of recovering the lease from hdfs, we try to recover lease in the `FSWAL.java` during `acquireLease()`, which was throwing 
```
org.apache.kafka.connect.errors.DataException: Error closing hdfs://10.75.172.215:8020/user/cloud-user/connect//logs/test_hdfs/0/log
        at io.confluent.connect.hdfs.wal.FSWAL.close(FSWAL.java:158)
        at io.confluent.connect.hdfs.wal.FSWAL.append(FSWAL.java:63)

```
To recover the lease, the following code was used:
 ```
public void recoverLease(){
 if (logFile != null && fileSystem instanceof DistributedFileSystem){
	  try {
		  log.info("Recovering lease for {}", logFile);
		  ((DistributedFileSystem) fileSystem).recoverLease(new Path(logFile));
	  }
	  catch (IOException ex) {
		  log.info("Recovering lease failed for {}", logFile);
	  }
          catch (Exception e){
                log.info(e.getMessage());
  }
}
}
```
`recoverLease()` is called within `acquireLease()` and `close()` in FSWAL.java
This causes the `recoverLease()` to be called but runs into a `NullPointerException` without any other details.
```
java.lang.NullPointerException
        at io.confluent.connect.hdfs.wal.FSWAL.recoverLease(FSWAL.java:112)
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:96)
        at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:132)
        at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:606)
        at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:261)

```
 The configurations have been verified and are correct. We are using Confluent 5.0.0 with CDH 5.16
Any help is appreciated.

**Comment by kaushiksrinivas** [comment]
Using file system object present within storage object of FSWAL solved this issue.

**Comment by beregon87** [comment]
I'm not sure what the problem is here. HDFS does not have HA with only 1 datanode, so you would of course expect errors if you shut it down.
