### ISSUE TITLE
HDFSSink Connector to Kerberized Hive Cluster (Azure HDInsights)

### ISSUE THREAD

**Issue by akgopal** [confluentinc/kafka-connect-hdfs#432]
We are hosting a single broker distributed Kafka connect HDFS sink connector and running into the below error when trying to write to a secured HA cluster.

**Connector Configuration**
       "hadoop.home": "/opt/connectors/hadoop",
       "hadoop.conf.dir": "/opt/connectors/hadoop/conf",
       "hdfs.url": "adl://prod01.azuredatalakestore.net",
       "hive.integration": "true",
       "hive.metastore.uris": "thrift://hn0-prod.contosos.onmicrosoft.com:9083,thrift://hn1-prod.contosos.onmicrosoft.com:9083",
       "hive.database": "temp",  
       "hdfs.authentication.kerberos": "true",
       "connect.hdfs.principal": "svc@CONTOSOS.ONMICROSOFT.COM",
       "connect.hdfs.keytab": "/opt/connectors/security/svc.keytab",
       "hdfs.namenode.principal": "nn/hn1-prod.contosos.onmicrosoft.com@CONTOSOS.ONMICROSOFT.COM",

hadoop client conf from the cluster has been copied over to the kafka connect broker.  The setup works without hive integration.  Please help.

**Error**
[2019-05-03 19:24:40,872] INFO Trying to connect to metastore with URI thrift://hn1-prod.contosos.onmicrosoft.com:9083 (hive.metastore:444)
[2019-05-03 19:24:41,419] WARN set_ugi() not successful, Likely cause: new client talking to old server. Continuing without it. (hive.metastore:512)
org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:380)
...
[2019-05-03 19:24:41,419] INFO Connected to metastore. (hive.metastore:540)
[2019-05-03 19:24:41,420] ERROR Got exception: org.apache.thrift.transport.TTransportException null (hive.log:1254)
org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
...
[2019-05-03 19:24:41,420] ERROR Converting exception to MetaException (hive.log:1255)
[2019-05-03 19:24:41,421] WARN Error closing output stream. (org.apache.thrift.transport.TIOStreamTransport:112)
java.net.SocketException: Socket closed

**Comment by akgopal** [comment]
The issue was due to missing hive.home.dir in the config.
