### ISSUE TITLE
Hive integration create table exception

### ISSUE THREAD

**Issue by GrapeBaBa** [confluentinc/kafka-connect-hdfs#443]
my sink config
```       "_comment": "Stream data to hive from Kafka topic using Hdfs3SinkConnector",
        "connector.class": "io.confluent.connect.hdfs3.Hdfs3SinkConnector",

        "_comment": "Deserialise the message key data from Avro",
        "key.converter": "io.confluent.connect.avro.AvroConverter",

        "_comment": "Since the data is in Avro, we need to provide the schema registry in order to look up the schema of the message",
        "key.converter.schema.registry.url": "http://localhost:8081",

        "_comment": "As above, but for the value of the message",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter.schema.registry.url": "http://localhost:8081",

        "_comment": "--- hive specific configuration here ---",
        "_comment": "hdfs url to which data should be written",
        "hdfs.url": "hdfs://localhost:9000",
        "_comment": "number of records to commit",
        "flush.size": "3",
        "hive.integration": "true",
        "hive.database":"test_db",
        "hive.metastore.uris": "thrift://localhost:9083",
        "schema.compatibility": "BACKWARD",

        "_comment": "Which topic(s) to write data from",
        "topics": "mysql_foobar"`
 ```
   

but got exception below
```
[2019-07-25 21:49:41,492] WARN Hive database already exists: default (io.confluent.connect.storage.hive.HiveMetaStore:172)
[2019-07-25 21:49:41,495] INFO committing files after waiting for rotateIntervalMs time but less than flush.size records available. (io.confluent.connect.hdfs3.TopicPartitionWriter:408)
[2019-07-25 21:49:41,523] ERROR Creating Hive table threw unexpected error (io.confluent.connect.hdfs3.TopicPartitionWriter:798)
io.confluent.connect.storage.errors.HiveMetaStoreException: Hive MetaStore exception
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:99)
        at io.confluent.connect.storage.hive.HiveMetaStore.createTable(HiveMetaStore.java:223)
        at io.confluent.connect.hdfs3.avro.AvroHiveUtil.createTable(AvroHiveUtil.java:52)
        at io.confluent.connect.hdfs3.DataWriter$3.createTable(DataWriter.java:285)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$1.call(TopicPartitionWriter.java:796)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$1.call(TopicPartitionWriter.java:792)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: MetaException(message:java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: hdfs://localhost:9000./null/topics/mysql_foobar)
```  
How the url hdfs://localhost:9000./null/topics/mysql_foobar concat? Why a .null/ path in it?

**Comment by GrapeBaBa** [comment]
anyone can help?

**Comment by GrapeBaBa** [comment]
I finally fixed this issue by set store.url in sink config file. I think the official document for hdfs connect should be updated.

**Comment by sureshchoudhay** [comment]
@GrapeBaBa Can you please tell me what URL we need to give? I have already given hdfs.url and thriftserver url. I am getting same error.

**Comment by abhisheksahani** [comment]
@sureshchoudhay  did you got the answer for this i am also facing the same issue

**Comment by sureshchoudhay** [comment]
"hdfs.url": "hdfs://localhost:9000"
"store.url": "hdfs://localhost:9000"
both are required...
