### ISSUE TITLE
Error serializing Avro message {} ;java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by jdang67** [confluentinc/kafka-connect-hdfs#444]
Hello Everyone,

If I connect to the local broker then it works, but try to connect the one on the dev server then I have exception below and not sure how to fix it.
FYI, the message payload is about 1kb.

thanks,
Jdang 

``` java
Error serializing Avro message 
{}
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:191)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:235)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:326)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:318)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:313)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:119)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:156)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:79)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:60)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:877)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:839)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:726)
```

**Comment by jdang67** [comment]
Looks like I report the problem to the wrong repo
