### ISSUE TITLE
adding a custom partitioner for hdfs connector giving error

### ISSUE THREAD

**Issue by abhisheksahani** [confluentinc/kafka-connect-hdfs#448]
We have created a custom partitioner whose behaviour is same as FieldPartitioner but we are passing the timestamp field from which we are deriving current year,month,date and hour and adding it to partition fields. for this we extend the current existing FieldPartitioner and added changes . Now on pointing partitioner.class to our new extended FieldPartitioner we are getting null pointer exception. can someone explain how to add custome partitioner.

code changes:
@Override
	public String encodePartition(SinkRecord sinkRecord) {
		Object value = sinkRecord.value();
		if (timePartitonFieldName == null || timePartitonFieldName.trim().isEmpty()) {
			throw new PartitionException("Error encoding partition.");
		}
		if (timeZoneString == null || timeZoneString.trim().isEmpty()) {
			throw new PartitionException("Error encoding partition.");
		}

		StringBuilder builder = new StringBuilder();
		Struct original;
		if (value instanceof Struct) {
			original = (Struct) value;
			final Schema valueSchema = sinkRecord.valueSchema();
			final Struct struct = (Struct) value;

			for (String fieldName : fieldNames) {
				if (builder.length() > 0) {
					builder.append(this.delim);
				}

				Object partitionKey = struct.get(fieldName);
				Type type = valueSchema.field(fieldName).schema().type();
				switch (type) {
				case INT8:
				case INT16:
				case INT32:
				case INT64:
					Number record = (Number) partitionKey;
					builder.append(fieldName + "=" + record.toString());
					break;
				case STRING:
					builder.append(fieldName + "=" + (String) partitionKey);
					break;
				case BOOLEAN:
					boolean booleanRecord = (boolean) partitionKey;
					builder.append(fieldName + "=" + Boolean.toString(booleanRecord));
					break;
				default:
					log.error("Type {} is not supported as a partition key.", type.getName());
					throw new PartitionException("Error encoding partition.");
				}
			}
			// return builder.toString();
		} else {
			log.error("Value is not Struct type.");
			throw new PartitionException("Error encoding partition.");
		}

		Object systime = original.get(timePartitonFieldName);
		Number millissystime = (Number) systime;

		Date date = new Date(millissystime.longValue());
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss:SSS", Locale.ENGLISH);
		sdf.setTimeZone(TimeZone.getTimeZone((String) original.get(timeZoneString)));
		String formattedDate = sdf.format(date);
		System.out.println(formattedDate); // Tuesday,November 1,2011 12:00,AM
		String[] dates = formattedDate.split("/");
		String year = dates[0];
		String month = dates[1];
		String dayAndTime = dates[2];
		String[] daytime = dayAndTime.trim().split(" ");
		String day = daytime[0];
		String hour = daytime[1].trim().split(":")[0];
		return builder.append("/year=" + year).append("/month=" + month).append("/day=" + day).append("/hour=" + hour)
				.toString();

REQUEST:
POST /connectors HTTP/1.1
Host: ...:8083
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 86d4ecc4-885e-f30c-ed03-309167c78474

{
"name": "hdfs-sink-connectornew4",
"config": {
"connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
"tasks.max": "1",
"hdfs.url": "hdfs://...:9000",
"hadoop.conf.dir": "/home/hadoop/hadoop/etc/hadoop/",
"hadoop.home": "/home/hadoop/hadoop/",
"hive.conf.dir": "/home/hadoop/apache-hive-2.3.5-bin/conf/",
"hive.home": "/home/hadoop/apache-hive-2.3.5-bin/",
"flush.size": "10000",
"format.class": "io.confluent.connect.hdfs.parquet.ParquetFormat",
"hive.integration": "true",
"hive.database": "testhdfsnew4",
"hive.metastore.uris": "thrift://...:9083",
"schema.compatibility": "BACKWARD",
"partitioner.class": "io.confluent.connect.storage.partitioner.FieldPartitionerWithTimePartition",
"partition.field.name": "type",
"partition.field.name.with.time":"time",
"timezone":"IST",

"topics": "testhdfsnew4"
}
}

stack trace :
at io.confluent.connect.storage.partitioner.PartitionerConfig.classNameEquals(PartitionerConfig.java:269)
at io.confluent.connect.storage.partitioner.PartitionerConfig.access$000(PartitionerConfig.java:32)
at io.confluent.connect.storage.partitioner.PartitionerConfig$PartitionerClassDependentsRecommender.visible(PartitionerConfig.java:237)
at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:611)
at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:619)
at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:527)
at org.apache.kafka.common.config.ConfigDef.validateAll(ConfigDef.java:510)
at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:492)
at org.apache.kafka.connect.connector.Connector.validate(Connector.java:135)
at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:282)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:537)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:534)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:270)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by ncliang** [comment]
@abhisheksahani Have you seen https://github.com/jametson/monaka ? Does this help you at all with the NPE? Specifically, the part about dropping the jar into ` $CONFLUENT_HOME/share/java/kafka-connect-hdfs/` before referencing your custom partitioner in `partitioner.class`.

HTH

**Comment by abhisheksahani** [comment]
@ncliang it is not an issue/bug, the jar path was not correct so closing it.
