### ISSUE TITLE
ERROR Failed creating a WAL Writer

### ISSUE THREAD

**Issue by alex-lx** [confluentinc/kafka-connect-hdfs#476]
Our hdfs-sink is configured for about 200 topics, after running for a while, the kafka-connector worker(which runs on k8s and memory limit is 4GB) was OOMed, and the connector report the `Failed creating a WAL Writer` error.
```
[2019-11-29 02:59:55,375] INFO Cannot acquire lease on WAL hdfs:// xxx.xxx.xxx.xxx//xxx/xxx/0/log (io.confluent.connect.hdfs.wal.FSWAL)
[2019-11-29 02:59:56,054] ERROR Failed creating a WAL Writer: Failed to APPEND_FILE /xxx/xxx/0/log for DFSClient_NONMAPREDUCE_xxxx on xxx.xxx.xxx.xxx because this file lease is currently owned by DFSClient_NONMAPREDUCE_-xxx on xxx
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2963)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2714)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3013)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2981)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:659)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:421)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2137)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2133)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1727)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2133)
 (io.confluent.connect.hdfs.wal.WALFile)
```

Here the connector's config:

```
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
partition.duration.ms=86400000
topics.dir=/delta_v2
flush.size=1000
schema.compatibility=BACKWARD
tasks.max=10
timezone=+0800
hdfs.url=hdfs://xxx
transforms=tombstoneHandler
hive.database=delta_v2
hive.metastore.uris=thrift://xxx
topics.regex=delta.*
locale=en-US
logs.dir=/delta_logs_v2
transforms.tombstoneHandler.type=io.confluent.connect.transforms.TombstoneHandler
format.class=io.confluent.connect.hdfs.avro.AvroFormat
hive.integration=true
partitioner.class=io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner
transforms.tombstoneHandler.behavior=ignore
rotate.schedule.interval.ms=300000
path.format='dt'=YYYY-MM-dd
```

Environment Information:
Kafka connector version: confluent community 5.3.1
Kafka broker version: 2.2.0
hdfs version: 2.7.2

**Comment by ncliang** [comment]
@alex-lx the WAL error doesn't seem related to OOM. For OOM, I think you can look at a few things:
- what is the heap size connect worker is getting? This is usually `-Xms`, `-Xmx`  parameters on the commandline to java.
- For k8s OOMKilled, it may be because Java memory allocation does not take into account cgroup memory limit. Maybe try some suggestions in this [post](https://banzaicloud.com/blog/java-resource-limits/) to see if it helps.
- `HeapDumpOnOutOfMemoryError` option to JVM can help generate heap dump for later analysis. Other useful options are `PrintGC` ones that print out information about JVM GC.
- You can use JMX to monitor the heap usage https://docs.confluent.io/current/kafka/monitoring.html#kafka-monitoring
- 4G for 200 topics seems low if throughput is relatively high. See some deployment and sizing suggestions [here](https://docs.confluent.io/current/connect/userguide.html#deployment-considerations)

**Comment by alex-lx** [comment]
@ncliang Thanks for your response.
This issue was 15 ago, and I'm afraid I've missed some import details on it. And our connector is working well now after several failures. Anyway, Your suggestions are very useful. Thanks again.
