### ISSUE TITLE
Renewing Kerberos ticket is not working

### ISSUE THREAD

**Issue by hwkim94** [confluentinc/kafka-connect-hdfs#478]
hello, kafka-connect-hdfs!
I have problem about renewing kerberos ticket

I met following error 1 week after running the program
```bash
[2019-12-13 01:03:44,964] WARN Couldn't setup connection for <principal> to <namenode>:8020 (org.apache.hadoop.ipc.Client)
org.apache.hadoop.ipc.RemoteException(javax.security.sasl.SaslException): GSS initiate failed
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:376)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        at org.apache.hadoop.ipc.Client.call(Client.java:1451)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy44.renewLease(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.renewLease(ClientNamenodeProtocolTranslatorPB.java:590)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy45.renewLease(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.renewLease(DFSClient.java:892)
        at org.apache.hadoop.hdfs.LeaseRenewer.renew(LeaseRenewer.java:423)
        at org.apache.hadoop.hdfs.LeaseRenewer.run(LeaseRenewer.java:448)
        at org.apache.hadoop.hdfs.LeaseRenewer.access$700(LeaseRenewer.java:71)
        at org.apache.hadoop.hdfs.LeaseRenewer$1.run(LeaseRenewer.java:304)
        at java.lang.Thread.run(Thread.java:748)


[2019-12-13 01:03:44,965] WARN Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.renewLease over <namenode>:8020. Not retrying because failovers (15) exceeded maximum allowed (15) (org.apache.hadoop.io.retry.RetryInvocationHandler)
java.io.IOException: Failed on local exception: java.io.IOException: Couldn't setup connection for <principal> to <namenode>:8020; Host Details : local host is: "<kafka-connect server>"; destination host is: "<namenode>":8020;
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
        at org.apache.hadoop.ipc.Client.call(Client.java:1479)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy44.renewLease(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.renewLease(ClientNamenodeProtocolTranslatorPB.java:590)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy45.renewLease(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.renewLease(DFSClient.java:892)
        at org.apache.hadoop.hdfs.LeaseRenewer.renew(LeaseRenewer.java:423)
        at org.apache.hadoop.hdfs.LeaseRenewer.run(LeaseRenewer.java:448)
        at org.apache.hadoop.hdfs.LeaseRenewer.access$700(LeaseRenewer.java:71)
        at org.apache.hadoop.hdfs.LeaseRenewer$1.run(LeaseRenewer.java:304)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Couldn't setup connection for <principal> to <namenode>:8020
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:679)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:737)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        at org.apache.hadoop.ipc.Client.call(Client.java:1451)
        ... 16 more
Caused by: org.apache.hadoop.ipc.RemoteException(javax.security.sasl.SaslException): GSS initiate failed
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:376)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        ... 19 more
```

with setting
```bash
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=3
topics=<topic>
format.class=io.confluent.connect.hdfs.string.StringFormat

hdfs.url=hdfs://myhdfs/user/mydir/kafkaData/
hadoop.conf.dir=/etc/hadoop/conf
flush.size=100
rotate.interval.ms=120000
partitioner.class=io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner
partition.duration.ms=600000
path.format=YYYYMMdd/HHmm
locale=kor
timezone=Asia/Seoul

hdfs.authentication.kerberos=true
connect.hdfs.principal=<prinipal>
connect.hdfs.keytab=<keytab>
hdfs.namenode.principal=nn/_HOST@<principal>
```

For testing kerberos re-login, I change setting as `kerberos.ticket.renew.period.ms=120000`
but there is any log for re-login

By [DataWriter.class](https://github.com/confluentinc/kafka-connect-hdfs/blob/5a5c9900cc9f01e6854f204530713b1638fbed51/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L177), ticket renew thread must call `ugi.reloginFromKeytab()` and in [ugi.reloginFromKeytab()](https://github.com/hanborq/hadoop/blob/99babec26a5f42021c0ec2a39ee7dbad4387b176/src/core/org/apache/hadoop/security/UserGroupInformation.java#L789), the function must logging about re-login

but, I cannot found any log about it.... Is there any solution for this situation?
Thanks for your favor

**Comment by ncliang** [comment]
The link you give for relogin seems to be for a fork based on an older (2012) Hadoop. Here is the one for 2.7.3 - https://github.com/apache/hadoop/blob/branch-2.7.3/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L1035

You can see that log level for those messages has been changed to DEBUG. Maybe try again with DEBUG log level and see if you can find those "Initiating re-login for... " messages in logs?

**Comment by hwkim94** [comment]
@ncliang 

thanks, it works!
