### ISSUE TITLE
Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted.

### ISSUE THREAD

**Issue by hwkim94** [confluentinc/kafka-connect-hdfs#481]
Hello KafkaConnect, alway thanks to your platform!

I met following error yesterday. But I can't info about this error.
When we met error, we were doing big map-reduce job at the same hadoop cluster.

Can you say me what is reason of this error and the solution to overcome?
Is this because another big MR job takes all resource of hadoop cluster?

```
[2020-01-11 23:02:40,699] ERROR WorkerSinkTask{id=fdc_analysis-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at io.confluent.connect.hdfs.string.StringRecordWriterProvider$1.close(StringRecordWriterProvider.java:88)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:680)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:687)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:420)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:57)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2280)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1343)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
[2020-01-11 23:02:40,799] ERROR WorkerSinkTask{id=fdc_analysis-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at io.confluent.connect.hdfs.string.StringRecordWriterProvider$1.close(StringRecordWriterProvider.java:88)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:680)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:687)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:420)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        ... 10 more
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:57)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2280)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1343)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
[2020-01-11 23:02:40,799] ERROR WorkerSinkTask{id=fdc_analysis-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-01-11 23:02:41,774] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:41,774] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] Revoking previously assigned partitions [nsp_pay_event_detail-2] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-01-11 23:02:41,917] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:42,094] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:42,094] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Revoking previously assigned partitions [nsp_pay_event_detail-1] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-01-11 23:02:42,110] ERROR Error closing writer for nsp_pay_event_detail-1. Error: java.io.EOFException: Premature EOF: no length prefix available (io.confluent.connect.hdfs.DataWriter)
[2020-01-11 23:02:42,110] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:42,116] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] Successfully joined group with generation 4 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:42,116] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Successfully joined group with generation 4 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:02:42,116] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] Setting newly assigned partitions [nsp_pay_event_detail-2] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-01-11 23:02:42,116] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Setting newly assigned partitions [nsp_pay_event_detail-1, nsp_pay_event_detail-0] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-01-11 23:02:42,118] INFO [Consumer clientId=consumer-3, groupId=fdc_analysis] Resetting offset for partition nsp_pay_event_detail-2 to offset 23075873. (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-01-11 23:02:42,118] INFO Started recovery for topic partition nsp_pay_event_detail-2 (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:02:42,118] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Resetting offset for partition nsp_pay_event_detail-0 to offset 23075842. (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-01-11 23:02:42,187] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Resetting offset for partition nsp_pay_event_detail-1 to offset 23079023. (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-01-11 23:02:42,188] INFO Started recovery for topic partition nsp_pay_event_detail-1 (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:02:42,211] INFO Successfully acquired lease for hdfs://npay/user/do/kafkaData/nsp/logs/nsp_pay_event_detail/2/log (io.confluent.connect.hdfs.wal.FSWAL)
[2020-01-11 23:02:45,111] INFO Finished recovery for topic partition nsp_pay_event_detail-1 (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:02:45,112] INFO Started recovery for topic partition nsp_pay_event_detail-0 (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:02:46,691] INFO Finished recovery for topic partition nsp_pay_event_detail-2 (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:03:02,582] ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED (io.confluent.connect.hdfs.TopicPartitionWriter)
org.apache.kafka.connect.errors.DataException: Error creating writer for log file hdfs://npay/user/do/kafkaData/nsp/logs/nsp_pay_event_detail/0/log
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
        at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
        at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:626)
        at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
        at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:380)
        at io.confluent.connect.hdfs.DataWriter.open(DataWriter.java:444)
        at io.confluent.connect.hdfs.HdfsSinkTask.open(HdfsSinkTask.java:133)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:612)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:69)
        at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:672)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:283)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:422)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:343)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1181)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:444)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:317)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-167600381-10.107.122.206-1573130207495:blk_1075520374_1779956 file=/user/do/kafkaData/nsp/logs/nsp_pay_event_detail/0/log
        at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:984)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:642)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:882)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:934)
        at java.io.DataInputStream.readFully(DataInputStream.java:195)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at io.confluent.connect.hdfs.wal.WALFile$Reader.init(WALFile.java:579)
        at io.confluent.connect.hdfs.wal.WALFile$Reader.initialize(WALFile.java:546)
        at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:462)
        at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:163)
        at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:77)
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)
        ... 28 more
[2020-01-11 23:03:02,597] INFO Starting commit and rotation for topic partition nsp_pay_event_detail-1 with start offsets {20200111/2300=23078940} and end offsets {20200111/2300=23079039} (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:03:02,611] ERROR Exception on topic partition nsp_pay_event_detail-1:  (io.confluent.connect.hdfs.TopicPartitionWriter)
org.apache.kafka.connect.errors.ConnectException: java.io.EOFException: Premature EOF: no length prefix available
        at io.confluent.connect.hdfs.string.StringRecordWriterProvider$1.close(StringRecordWriterProvider.java:90)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:680)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:687)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:386)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Premature EOF: no length prefix available
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2282)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1343)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
[2020-01-11 23:03:05,414] INFO committing files after waiting for rotateIntervalMs time but less than flush.size records available. (io.confluent.connect.hdfs.TopicPartitionWriter)
[2020-01-11 23:03:05,414] ERROR WorkerSinkTask{id=fdc_analysis-2} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at io.confluent.connect.hdfs.string.StringRecordWriterProvider$1.close(StringRecordWriterProvider.java:88)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:680)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:687)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:420)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Got error, status message , ack with firstBadLink as 10.107.122.79:1019
        at org.apache.hadoop.hdfs.protocol.datatransfer.DataTransferProtoUtil.checkBlockOpStatus(DataTransferProtoUtil.java:142)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1359)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
[2020-01-11 23:03:05,417] ERROR WorkerSinkTask{id=fdc_analysis-2} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at io.confluent.connect.hdfs.string.StringRecordWriterProvider$1.close(StringRecordWriterProvider.java:88)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:680)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:687)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:420)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        ... 10 more
Caused by: java.io.IOException: Got error, status message , ack with firstBadLink as 10.107.122.79:1019
        at org.apache.hadoop.hdfs.protocol.datatransfer.DataTransferProtoUtil.checkBlockOpStatus(DataTransferProtoUtil.java:142)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1359)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1262)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
[2020-01-11 23:03:05,417] ERROR WorkerSinkTask{id=fdc_analysis-2} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-01-11 23:03:06,241] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:03:09,244] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:03:12,247] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:03:15,249] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-11 23:03:18,252] INFO [Consumer clientId=consumer-2, groupId=fdc_analysis] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
```

**Comment by ncliang** [comment]
@hwkim94 the culprit would seem to be this
```
Caused by: java.io.IOException: Connection reset by peer
```
The `java.lang.IllegalArgumentException: Self-suppression not permitted` thing is because we get another IllegalArgumentException when we attempt to close the tmp file when handling the 1st exception.

This thread seems to indicate that it could be caused by GC pause in the datanode and increasing heap size may help. You mention that it happens at the same time you are running a MR job, so I suspect the cause may be similar.

https://community.cloudera.com/t5/Support-Questions/Connection-failed-to-DataNode-50075-sometimes/td-p/205044

Maybe try increase the heap size as the thread suggests, or tune GC on the datanode to use something like G1GC to minimize stop-the-world GC pauses.

**Comment by hwkim94** [comment]
thanks!! 
I solved this problem!

**Comment by moreiravictor** [comment]
@hwkim94 how did you solve it?

**Comment by moreiravictor** [comment]
> thanks!! I solved this problem!

@hwkim94 how did you solve it?
