### ISSUE TITLE
Error serializing Avro message

### ISSUE THREAD

**Issue by rakeshbgupta** [confluentinc/kafka-connect-hdfs#489]
HI, I am trying to send an GenericRecord (org.apache.avro.generic public interface GenericRecord extends IndexedRecord) to a kafka topic via the producer.send() method, and using the io.confluent.kafka.serializers.KafkaAvroSerializer to serialize it (which shd be accepted by the kafka).
Configs:
```
prodProp.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
prodProp.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
prodProp.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, KafkaAvroSerializer.class.getName());

GenericRecord avroRec =  new GenericData.Record(protoSchema);

avroRec.put("id",value.getAttributes().getId());
avroRec.put("xxxxxxxxxxxxx",value.getAttributes().getxxxxxxxx());
avroRec.put("yyyyyyyy",value.getAttributes().getyyyyyyyyy());
......
...
..


ProducerRecord producerRec = new ProducerRecord<String, GenericRecord>("topicname", value.getId(), avroRec);
producer.send(producerRec);
```

The schema and the generic record is generated from the protobuf objects.
But when we send the avro records to the kafka topic (using the avro serializer), I receive a serialization exception as below:

```

Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.ClassCastException: com.google.protobuf.StringValue cannot be cast to java.lang.CharSequence
	at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:323)
	at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:315)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:150)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:72)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:95)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:903)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
```

Anyone has any idea about the above?

**Comment by levzem** [comment]
@rakeshbgupta this is a repository for the HDFS connector. A better place would be to ask `apache/kafka`. For this reason I am closing this.
