### ISSUE TITLE
Kafka SFTP Connectors input directory error

### ISSUE THREAD

**Issue by shadow111** [confluentinc/kafka-connect-hdfs#519]
im using confluent sftp connectors to stream data from a remote sftp server here my .properties file for the connector:

```
name=SftpSourceConnector
tasks.max=1
behavior.on.error=IGNORE
connector.class=io.confluent.connect.sftp.SftpCsvSourceConnector
cleanup.policy=MOVE
input.path=/home/user/source
error.path=/home/user/error
finished.path=/home/user/output
input.file.pattern=sample.csv
sftp.username=user
sftp.password=pass
sftp.host=host
sftp.port=22
kafka.topic=sftp-topic-0
schema.generation.enabled=true
```

the 3 directories /home/user/source, /home/user/error, /home/user/output exist and they are writable , but when running the connectors it says that the input directory doesn't exist

```
ERROR WorkerConnector{id=SftpSourceConnector} Error while starting connector 
 (org.apache.kafka.connect.runtime.WorkerConnector)
 org.apache.kafka.connect.errors.ConnectException: Sftp directory for 'input.path''\home\user\source' 
  does not exist at 

 io.confluent.connect.sftp.source.SftpDirectoryPermission.
 directoryExist(SftpDirectoryPermission.java:66)
io.confluent.connect.sftp.source.SftpDirectoryPermission.
  ensureReadable(SftpDirectoryPermission.java:44)
    at io.confluent.connect.sftp.SftpCsvSourceConnector.start(SftpCsvSourceConnector.java:55)
    at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)
    at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)
    at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
    at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.s
     tartConnector(StandaloneHerder.java:295)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.
    putConnectorConfig(StandaloneHerder.java:211)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
   Caused by: 2: No such file
    at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2873)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2225)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2242)
    at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2199)
    at io.confluent.connect.sftp.source.SftpDirectoryPermission.
   directoryExist(SftpDirectoryPermission.java:62)
```

**Comment by OneCricketeer** [comment]
This is not the appropriate repo for this issue
