### ISSUE TITLE
HDFS3 sink and Hive Integration Hive 2.1.1 (get_table_req)

### ISSUE THREAD

**Issue by j-metsfan** [confluentinc/kafka-connect-hdfs#533]
Using hdfs3 sink with Hadoop 3.0.0 and Hive 2.1.1
Files are written to HDFS, Hive table is created, but adding partitions results in below error

It seems method 'get_table_req' does not exist in Hive 2.1.1 metastore. Is there a way to have hive integration use Hive metastore API supported by Hive 2.1.1

[2020-12-09 19:11:33,355] ERROR Altering Hive schema threw unexpected error (io.confluent.connect.hdfs3.TopicPartitionWriter)
io.confluent.connect.storage.errors.HiveMetaStoreException: Exception communicating with the Hive MetaStore
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:101)
        at io.confluent.connect.storage.hive.HiveMetaStore.getTable(HiveMetaStore.java:303)
        at io.confluent.connect.hdfs3.avro.AvroHiveUtil.alterSchema(AvroHiveUtil.java:61)
        at io.confluent.connect.hdfs3.DataWriter$3.alterSchema(DataWriter.java:288)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$2.call(TopicPartitionWriter.java:812)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$2.call(TopicPartitionWriter.java:808)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:2079)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:2066)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1578)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1570)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208)
        at com.sun.proxy.$Proxy53.getTable(Unknown Source)
        at io.confluent.connect.storage.hive.HiveMetaStore$9.call(HiveMetaStore.java:294)
        at io.confluent.connect.storage.hive.HiveMetaStore$9.call(HiveMetaStore.java:290)
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:97)
        ... 9 more
[2020-12-09 19:11:33,363] ERROR Adding Hive partition threw unexpected error (io.confluent.connect.hdfs3.TopicPartitionWriter)
io.confluent.connect.storage.errors.HiveMetaStoreException: Invalid partition for default.table3: year=2020/month=12/day=09/hour=13/minute=11/second=30
        at io.confluent.connect.storage.hive.HiveMetaStore$1.call(HiveMetaStore.java:122)
        at io.confluent.connect.storage.hive.HiveMetaStore$1.call(HiveMetaStore.java:107)
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:97)
        at io.confluent.connect.storage.hive.HiveMetaStore.addPartition(HiveMetaStore.java:132)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$3.call(TopicPartitionWriter.java:827)
        at io.confluent.connect.hdfs3.TopicPartitionWriter$3.call(TopicPartitionWriter.java:823)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: InvalidObjectException(message:@hive#default.table3 table not found)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$append_partition_by_name_result$append_partition_by_name_resultStandardScheme.read(ThriftHiveMetastore.java)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$append_partition_by_name_result$append_partition_by_name_resultStandardScheme.read(ThriftHiveMetastore.java)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$append_partition_by_name_result.read(ThriftHiveMetastore.java)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_append_partition_by_name(ThriftHiveMetastore.java:2557)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.append_partition_by_name(ThriftHiveMetastore.java:2542)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.appendPartition(HiveMetaStoreClient.java:722)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.appendPartition(HiveMetaStoreClient.java:716)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208)
        at com.sun.proxy.$Proxy53.appendPartition(Unknown Source)
        at io.confluent.connect.storage.hive.HiveMetaStore$1.call(HiveMetaStore.java:114)
        ... 9 more

connector config:

{
  "name": "hdfs3-sink23",
  "config": {
    "connector.class": "io.confluent.connect.hdfs3.Hdfs3SinkConnector",
    "tasks.max": "1",
    "topics": "table3",
    "hdfs.url": "hdfs://nameservice",
    "store.url": "hdfs://nameservice",
    "flush.size": "3",
    "hive.conf.dir": "/etc/hive/conf",
    "hive.integration": "true",
    "schema.compatibility": "BACKWARD",
    "hive.metastore.uris": "thrift://metastorehost:9083",
    "hadoop.home": "/opt/cloudera/parcels/CDH/lib/hadoop",
    "hive.home": "/opt/cloudera/parcels/CDH/lib/hive",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://confluentschemaregistryhost:8081",
    "schema.registry.url": "http://confluentschemaregistryhost:8081",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://confluentschemaregistryhost:8081",
    "confluent.topic.bootstrap.servers": "kafkabroker:9092",
    "confluent.topic.replication.factor": "1",
    "hdfs.authentication.kerberos": "true",
    "hadoop.conf.dir": "/etc/hadoop/conf",
    "connect.hdfs.principal": "username1@USDADEV.AIP",
    "connect.hdfs.keytab": "/keytabs/username1.keytab",
    "hdfs.namenode.principal": "hdfs/_HOST@USDADEV.AIP",
    "format.class": "io.confluent.connect.hdfs3.avro.AvroFormat",
    "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "path.format": "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH/'minute'=mm/'second'=ss",
    "partition.duration.ms": "30000",
    "locale": "en-US",
    "timezone": "America/Chicago"
  }
}

**Comment by manpreet1992** [comment]
We are also facing the same issue. Any updates on this issue?
