### ISSUE TITLE
Facing issue while trying to get data from postgres sql into kafka topics using debezium plugin

### ISSUE THREAD

**Issue by Snehil-upes** [confluentinc/kafka-connect-hdfs#555]
Here is the issue that I am facing:
 ERROR WorkerSourceTask{id=Trail-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
org.apache.kafka.connect.errors.ConnectException: Invalid metric name 'debezium.postgres:type=connector-metrics,context=snapshot,server=localhost:5432/snehildb'
        at io.debezium.metrics.Metrics.metricName(Metrics.java:92)
        at io.debezium.metrics.Metrics.<init>(Metrics.java:34)
        at io.debezium.pipeline.metrics.PipelineMetrics.<init>(PipelineMetrics.java:44)
        at io.debezium.pipeline.metrics.SnapshotChangeEventSourceMetrics.<init>(SnapshotChangeEventSourceMetrics.java:46)
        at io.debezium.pipeline.metrics.DefaultChangeEventSourceMetricsFactory.getSnapshotMetrics(DefaultChangeEventSourceMetricsFactory.java:21)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.start(ChangeEventSourceCoordinator.java:82)
        at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:215)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by OneCricketeer** [comment]
@Snehil-upes Please close this and open the issue in the appropriate Debezium github repository
