### ISSUE TITLE
Exception in log during shutdown

### ISSUE THREAD

**Issue by 13h3r** [confluentinc/kafka-connect-hdfs#63]
From time to time I got this in logs:

```
[2016-05-23 08:55:57,948] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@2245d31a Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2016-05-23 08:56:07,933] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@536bc87 Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2016-05-23 08:56:07,946] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@1bec52b1 Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
[2016-05-23 08:56:07,948] INFO org.apache.kafka.connect.runtime.WorkerSinkTask@2245d31a Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:187)
Exception in thread "Thread-0" java.lang.NullPointerException
	at io.confluent.connect.hdfs.DataWriter.close(DataWriter.java:307)
	at io.confluent.connect.hdfs.HdfsSinkTask.stop(HdfsSinkTask.java:83)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.awaitStop(WorkerSinkTask.java:119)
	at org.apache.kafka.connect.runtime.Worker.stopTask(Worker.java:311)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.removeConnectorTasks(StandaloneHerder.java:238)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.stop(StandaloneHerder.java:68)
	at org.apache.kafka.connect.runtime.Connect.stop(Connect.java:71)
	at org.apache.kafka.connect.runtime.Connect$ShutdownHook.run(Connect.java:93)
[2016-05-23 08:56:16,977] INFO Stopping task test1-bss-1 (org.apache.kafka.connect.runtime.Worker:305)
[2016-05-23 08:56:16,977] INFO Starting graceful shutdown of thread WorkerSinkTask-test1-bss-1 (org.apache.kafka.connect.util.ShutdownableThread:119)
```

I did not investigate this in deep yet.

Additional info that may be useful: I ran 3 tasks that reads writes to the same hadoop. This exception occurs during shutdown first of them. Other tasks was not shutdown properly (according to logs)

**Comment by Ishiihara** [comment]
@13h3r Which version of the connector are you running? master or 2.0.1? You may hit a bug that can cause concurrent `TopicPartitionWriter` close in 2.0.1.

**Comment by 13h3r** [comment]
It was 2.0.1

**Comment by GRpro** [comment]
Hi,
Could you please provide a link to commit that fixes the issue?
Thanks.
