### ISSUE TITLE
ERROR Unable to shutdown local metastore client 

### ISSUE THREAD

**Issue by xianzhen** [confluentinc/kafka-connect-hdfs#84]
[2016-06-28 15:27:28,638] ERROR Unable to shutdown local metastore client (hive.metastore:495)
org.apache.thrift.transport.TTransportException: java.net.SocketException: Socket closed
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161)
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
        at com.facebook.fb303.FacebookService$Client.send_shutdown(FacebookService.java:436)
        at com.facebook.fb303.FacebookService$Client.shutdown(FacebookService.java:430)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.close(HiveMetaStoreClient.java:492)
        at org.apache.hive.hcatalog.common.HiveClientCache$CacheableHiveMetaStoreClient.tearDown(HiveClientCache.java:403)
        at org.apache.hive.hcatalog.common.HiveClientCache$CacheableHiveMetaStoreClient.finalize(HiveClientCache.java:418)
        at java.lang.System$2.invokeFinalize(System.java:1213)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:159)
        ... 10 more

Hi, Why this happen, does it matter?

**Comment by ewencp** [comment]
@xianzhen Not sure, this looks like a finalizer is trying to clean up the metastore client but the connection has been closed. There's no code related to the HDFS connector in the stacktrace, so its not clear how the connector might trigger this. Given that the socket was closed, which presumably means the remote end closed it, I would expect this is either due to a timeout or the metastore itself closing the connection.

**Comment by cotedm** [comment]
This absolutely happens if the HMS is shutdown before the client gets shut down. There used to be race conditions on older versions of Hive that you would see this for during shutdown, but they are harmless from the perspective of this connector.
