### ISSUE TITLE
ERROR Uncaught exception in herder work thread

### ISSUE THREAD

**Issue by xianzhen** [confluentinc/kafka-connect-hdfs#85]
Version: 0.9.0

Steps:
1. Stop kafka connect.
2. Deleted  connect-configs & connector-offsets topics in kafka.;
3. Start kafka connect;
4. create connectors with some configs changed.

2016-06-28 11:39:40,487] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:166)
java.lang.NullPointerException
        at io.confluent.connect.hdfs.DataWriter.close(DataWriter.java:307)
        at io.confluent.connect.hdfs.HdfsSinkTask.stop(HdfsSinkTask.java:83)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.awaitStop(WorkerSinkTask.java:119)
        at org.apache.kafka.connect.runtime.Worker.stopTask(Worker.java:311)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.onRevoked(DistributedHerder.java:898)
        at org.apache.kafka.connect.runtime.distributed.WorkerCoordinator.onJoinPrepare(WorkerCoordinator.java:236)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:207)
        at org.apache.kafka.connect.runtime.distributed.WorkerGroupMember.ensureActive(WorkerGroupMember.java:130)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:182)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:159)
        at java.lang.Thread.run(Thread.java:745)
[2016-06-28 11:39:40,489] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:68)

I got something in log, connectors are stopped because of config update:
[2016-06-28 11:39:40,257] INFO Connector beaver_http_request-c3 config updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:827)
[2016-06-28 11:39:40,260] INFO Rebalance started (org.apache.kafka.connect.runtime.distributed.DistributedHerder:879)
[2016-06-28 11:39:40,260] INFO Stopping connector beaver_http_response-c3 (org.apache.kafka.connect.runtime.Worker:226)
[2016-06-28 11:39:40,260] INFO Stopped connector beaver_http_response-c3 (org.apache.kafka.connect.runtime.Worker:240)
[2016-06-28 11:39:40,260] INFO Stopping connector beaver_tcp_session-c3 (org.apache.kafka.connect.runtime.Worker:226)

**Comment by ewencp** [comment]
@xianzhen 0.9 is the version of the broker, but which version of the connector are you using? It looks like the assignment and set of TopicPartitionWriters somehow got out of sync, which should not be possible.

**Comment by xianzhen** [comment]
@ewencp Thanks. Confluent version is 2.0.0. I check the source, One possible reason is that WorkerSinkTask clear all TopicPartitionWriter before ConsumerSinkTask is closed. I am not sure.

**Comment by ewencp** [comment]
@xianzhen This has been fixed as of the [3.0.0 release](confluent.io/downloads). I think the issue was that `onPartitionsRevoked` was removing the `TopicPartitionWriters` but then `close()` was trying to use them. The newer version relies on the fact that the framework guarantees it will revoke the partitions before finally stopping the task.

**Comment by raju-divakaran** [comment]
I could see the same error popping up again and we are using confluent version 3.0.0!

This is mainly noticed in our staging setup, where we are having 3 kafka connect instances. So if I stop all 3 instances, start one by one this error comes up. Its like when one is started and when I start the second one the first dies. Then I start the first one the second dies. Eventually, I go through that cycle a couple of times to make it stable.

Also I think it happens at a particular stage, in the sense if I start all three together.. this happens. But when I start one by one really quick.. at times this is not noticed!

**Comment by ewencp** [comment]
@raju-divakaran Are there any other error messages or stacktraces earlier in the log? It looks like the null pointer is due to the consumer not being allocated yet. We protect against this in `WorkerSinkTask.close()` but not in `WorkerSinkTask.stop()`. But as far as I can tell, this shouldn't be a problem because the way the order in which we create & initialize the `WorkerSinkTask` (the latter half of which creates the consumer) and then add it to the collection of tasks, any calls to `Worker.stopTasks` shouldn't see the task until the consumer is already allocated. The only path I can see where this wouldn't happen is if there was an exception during `WorkerSinkTask.initialize`, in which case there should be an error message like `Task {} failed initialization and will not be started.` and a corresponding stack trace.

**Comment by Tseretyan** [comment]
I have similar issue. Version of confluent 2.0.1. 
1. Start worker in distributed mode in interactive mode (not daemon)
2. add connector with configuration
`{
 "name": "hdfs-test-ign",
 "config": {
 "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
 "tasks.max": "6",
 "topics": "test_ign",
 "hdfs.url": "hdfs://hdfsd:8020",
 "hadoop.conf.dir": "/confluent/hadoop/conf",
 "flush.size": "100",
 "partitioner.class": "io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner",
 "locale": "us",
 "partition.duration.ms": "86400000",
 "path.format": "YYYY-MM-dd",
 "timezone": "US/Eastern",
 "rotate.interval.ms": "60000"
 }
}`
3. send some messages
4. stop worker (Ctrl+C)
5. start worker again.

After some restarts I get error and the only way to make it work again is to delete config and offset topics.
Worker config as well as output log are attached.
[connect-avro-distributed.properties.txt](https://github.com/confluentinc/kafka-connect-hdfs/files/408013/connect-avro-distributed.properties.txt)
[distributed_consumer_fail_log.txt](https://github.com/confluentinc/kafka-connect-hdfs/files/408014/distributed_consumer_fail_log.txt)

**Comment by Tseretyan** [comment]
I found out what causes this error. It turns out that config topic had more than one partition. Once I created topic with one partition, the problem disappeared.

**Comment by blbradley** [comment]
@Tseretyan Thanks for sharing. I believe your information helped with some trouble I had with using connect-standalone.

**Comment by tnegi7519** [comment]
I am getting the same error on Kafka-Connect start. I have made the config topic with single partition.
I checked the zookeeper and Kafka. I can produce and consume message on "test"  topic.
My setup is single server with Zookeeper, Kafka, Schema registry, Kafka-connect on same server:

I get following exception in log:
---------------------------------
2016-10-20 04:42:15,915 - ERROR [DistributedHerder] (org.apache.kafka.connect.runtime.distributed.DistributedHerder.run:183) - Uncaught exception in herder work thread, exiting:
org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
2016-10-20 04:42:15,916 -  INFO [Thread-1] (org.apache.kafka.connect.runtime.Connect.stop:68) - Kafka Connect stopping
2016-10-20 04:42:15,916 -  INFO [Thread-1] (org.apache.kafka.connect.runtime.rest.RestServer.stop:154) - Stopping REST server
2016-10-20 04:42:15,917 - DEBUG [Thread-2] (org.eclipse.jetty.util.component.AbstractLifeCycle.setStopping:194) - stopping org.eclipse.jetty.server.Server@347d46d4

**Comment by cotedm** [comment]
@tnegi7519 your issue looks a bit different than the one reported here. It looks more like your worker is not able to fetch topic metadata which is different than a NullPointerException coming from TopicPartitionWriters getting out of sync. If you are still having trouble with a timeout fetching topic metadata, please open a new issue with more context around the logging and the worker/connector configs and we'll see if we can help on that issue.
